Description of convert_G_to_kG
Home > mnt > mnt-basic > mnt_kinetics > convenience > convert_G_to_kG.m
convert_G_to_kG
PURPOSE
[kG,kG_std] = convert_G_to_kG(G,RT,G_std)
SYNOPSIS
function [kG,kG_std] = convert_G_to_kG(G,RT,G_std)
DESCRIPTION
 [kG,kG_std] = convert_G_to_kG(G,RT,G_std)
CROSS-REFERENCE INFORMATION
This function calls:
convert_G_scale scale_G = convert_G_scale()
RT result = RT(temperature)
lognormal_log2normal [mu,sigma] = lognormal_log2normal(mu_log,sigma_log,convention)
This function is called by: