Description of convert_G_scale
Home > mnt > mnt-basic > mnt_kinetics > convenience > convert_G_scale.m
convert_G_scale
PURPOSE
scale_G = convert_G_scale()
SYNOPSIS
function scale_G = convert_G_scale()
DESCRIPTION
 scale_G = convert_G_scale()
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
convert_G_to_kG [kG,kG_std] = convert_G_to_kG(G,RT,G_std)
convert_kG_to_G [G,G_std] = convert_kG_to_G(kG,rt,kG_std)
convert_kG_to_kEQ kEQ = convert_kG_to_kEQ(kG,N,RT)
convert_log_g_to_log_q [log_q,log_q_cov] = convert_log_g_to_log_q(log_g,N,RT,log_g_cov)
network_velocities v = network_velocities(s,network,kinetics,split,indices,t)