Description of column
Home > mnt-basic > utils > column.m
column
PURPOSE
transform a vector (row or column) into a column vector
SYNOPSIS
function x = column(x)
DESCRIPTION
 transform a vector (row or column) into a column vector
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
parameter_balancing_task [task, prior] = parameter_balancing_task(network, kinetic_data, parameter_prior, model_quantities, basic_quantities,include_metabolic)
EBA_orth orthogonal = EBA_orth(sign_J,C)
network_efmtool [C,mnet] = network_efmtool(network, method, ind_ignore, zv)
pmf v = pmf(network,fba_constraints,benefit,v_start)
pmf_with_internal_production v = pmf(network,fba_constraints,benefit,v_start)
netgraph_cofactor_graphs [network_CoHid,network_CoSplit] = netgraph_cofactor_graphs(network, metabolites_to_be_omitted, layout_file, max_met_degree,metabolites_to_be_kept)
netgraph_flux_in_large_network [nn,M] = netgraph_flux_in_large_network(network,v,perc_show,table_positions,cofactors,not_cofactors,goptions_default)
netgraph_move network = netgraph_move(network,flag_draw_details,options,picture,filename_in,filename_out)
netgraph_print_positions [names, positions] = netgraph_print_positions(network,layout_file,offsets,policy,flag_KEGG_ids,flag_element_names,flag_fixed,flag_invisible)
netgraph_simple_graph [n2,keep_met,keep_react] = netgraph_simple_graph(n1,met_hide,met_fixed,met_fixed_positions,react_hide)
convenience2vector [vector,names,types,relevant_reactions] = convenience2vector(kinetics,network,no_names)
convenience_velocities v = convenience_velocities(s,network,kinetics,indices,split,scale_G,offset_ratio)
compute_modular_response_second [Rtarget_sc_u, Rtarget_sc_uu] = compute_modular_control_second(zc_scaled, zv_scaled, kinetic_law, N, W, ind_ext, alpha_A, alpha_I, alpha_M, v, A, u, c, h, v_plus_fallback, v_minus_fallback, CS_un, CJ_un)
modular_rate_law_to_sbtab quantity_table = modular_rate_law_to_sbtab(network,filename,options)
modular_par2vector [v,names] = modular_par2vector(p,network,no_names)
numeric_par2vector function v = par2vector(p)
response_coefficients_target_numerical [RZp,RZpp] = response_coefficients_target_numerical(network,c,ind_rel_par,zc,zv)
network_add_metabolites network = network_add_metabolites(network,new_metabolites,new_external);
network_add_reaction network = network_add_reaction(network,reactants,stoich_coeffs,name,reversible);
network_build_from_sum_formulae network = network_build_from_sum_formulas(filename_reactions,filename_compounds,columns)
network_construct network = network_construct(N,reversible,ind_external,metabolites,actions,no_graphics,regulation_matrix,flag_kinetics)
network_subnetwork [subnetwork, ind_m, ind_r] = network_subnetwork(network,ind_m,ind_r,omit_isolated_metabolites)
network_numbers [nr,nm,nx,KM_indices,KA_indices,KI_indices,nKM,nKA,nKI] = network_numbers(network)
replace_small_std substitute standard deviations below 'qquantile' by value at 'qquantile'
my_corrcoef [c, pvalue_one_tailed, pvalue_two_tailed] = my_corrcoef(A,B)
my_xticklabel