Description of RT
Home > mnt > mnt-basic > mnt_numbers > RT.m
RT
PURPOSE
result = RT(temperature)
SYNOPSIS
function result = RT(temperature)
DESCRIPTION
 result = RT(temperature)
CROSS-REFERENCE INFORMATION
This function calls:
ncsp_constants constants = ncsp_constants()
default commandstring = default(varname1,defaultvalue1,varname2,defaultvalue2,...)
This function is called by:
optimise_delta_mu_given_signs delta_mu = optimize_delta_mu_given_signs(N,parameter_prior,data,v,options)
optimise_mu_given_signs [delta_mu,delta_mu_score,this_mu] = optimize_mu_given_signs(N,parameter_prior,data,v,options,constraints)
eba_feasible_lp [eba_feasible, dmu, dmu_abs_max] = eba_feasible_lp(v,Ntot,dmu_fix,dmu_abs_min,epsilon,dmu_abs_max)
es_check_feasibility es_check_feasibility(N, v, delta_mu, mu0, c)
es_check_velocities_ma_ratios correct = es_check_velocities_ma_ratios(N,v,log_c,this_delta_mu)
sample_feasible_dmu [mu, success_flag] = sample_feasible_mu(N, ind_ext, v, es_constraints, es_options)
sample_feasible_mu [mu, success_flag] = sample_feasible_mu(N,ind_ext,v,constraints,options,method,n_sample)
mdf [c,A] = mdf(N, v, keq, mdf_options)
convenience_dependent_parameters res = convenience_dependent_parameters(network)
convenience_print s = convenience_print(kinetics,n,actions,network)
convert_G_to_kG [kG,kG_std] = convert_G_to_kG(G,RT,G_std)
compute_modular_elasticities E = compute_modular_elasticities(kinetic_law, N, W, ind_ext, alpha_A, alpha_I, alpha_M, v, A, u, c, h, v_plus_fallback, v_minus_fallback,flag_second_order)
compute_modular_elasticities_second E_target = compute_modular_elasticities_second(z,kinetic_law,N, W, ind_ext, alpha_A, alpha_I, alpha_M, v, A, u, c, h, v_plus_fallback, v_minus_fallback)
elasticities_to_parameters kinetics = elasticities_to_parameters(network,E_sc,v,c,u,A,h)
modular_rate_law_to_sbtab quantity_table = modular_rate_law_to_sbtab(network,filename,options)
ms_import_kinetic [kin_data,parameter_prior] = ms_import_kinetic(network,kinetic_balanced_file)
test_modular_rate_law r = test_moldular_rate_law(n,kinetics)
adjust_infeasible_A_and_Keq [Keq,A] = adjust_infeasible_A_and_Keq(v,Keq,A,A_min_adjusted);
thermo_pb [c,A] = thermo_pb(N, v, thermo_pb_options, verbose)
data_integration_load_kinetic_data kinetic_data = kinetic_data = data_integration_load_kinetic_data(data_quantities, parameter_prior, network, data_file, use_sbml_ids, use_kegg_ids, flag_invent_std, verbose, filter_column, filter_entry, reaction_column_name, compound_column_name)
parameter_balancing_Keq [Keq, mu0, c, my_kinetic_data] = parameter_balancing_Keq(network, filename,options)
parameter_balancing_construct_Q_matrix Q = parameter_balancing_construct_Q_matrix(quantities, basic_quantities, parameter_prior, network)
parameter_balancing_model_matrices
parameter_balancing_output [r_mode, r_mean, r_std, r_geom_mean, r_geom_std, r_orig, r_samples, r_flux_adjusted, r_flux_adjusted_std] = parameter_balancing_output(res,kinetic_data_orig,options)
pb_kinetic_data_adjust If desired, insert given Keq values
parameter_balancing_thermodynamic PARAMETER_BALANCING_THERMODYNAMIC Thermodynamic parameter balancing