Description of numbered_names
Home > mnt > util > numbered_names.m
numbered_names
PURPOSE
list = numbered_names(name,n_max)
SYNOPSIS
function list = numbered_names(name,n_max)
DESCRIPTION
 list = numbered_names(name,n_max)
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
convenience2vector [vector,names,types,relevant_reactions] = convenience2vector(kinetics,network,no_names)
modular_par2vector [v,names] = modular_par2vector(p,network,no_names)
network_build_from_sum_formulae network = network_build_from_sum_formulas(filename_reactions,filename_compounds,columns)
SOURCE CODE
function list = numbered_names(name,n_max)
% list = numbered_names(name,n_max)
if length(n_max)==1,
list=cell(n_max,1);
for it=1:n_max,
  list{it} = [name '_{' num2str(it) '}' ];
end
else
 list=cell(n_max(1),n_max(2));
 for it=1:n_max(1),
  for it2=1:n_max(2),
   list{it,it2} = [name '_{' num2str(it) '/' num2str(it2) '}'];
  end
 end
end
end