Description of control_coefficients_distribution
Home > mnt-advanced > mnt_uncertain_parameters > control_coefficients_distribution.m
control_coefficients_distribution
PURPOSE
[C_J_mean,C_J_std,C_S_mean, C_S_std, R_J_mean,R_J_std,R_S_mean,R_S_std] = control_coefficients_distribution(network,solution)
SYNOPSIS
function [C_J_mean,C_J_std,C_S_mean, C_S_std, R_J_mean,R_J_std,R_S_mean,R_S_std] = control_coefficients_distribution(network,solution)
DESCRIPTION
 [C_J_mean,C_J_std,C_S_mean, C_S_std, R_J_mean,R_J_std,R_S_mean,R_S_std] = control_coefficients_distribution(network,solution)
 compute the distribution of control coefficients etc in uncertain models
CROSS-REFERENCE INFORMATION
This function calls:
analyse_N [ K, L, NR, null_l, pinv_NR, independent_metabolites, N1] = analyse_N(N,external)
control_coefficients [CJ, CS, L_int, NR_int, M, M_adj, indp_among_internal] = control_coefficients(N, Ec, external, used, NR_int, L_int, indp_among_internal,dilution_rate)
response_coefficients [RS, RJ, RS2, RJ2] = response_coefficients(CS, Ec, Ep, Ecc, Ecp, Epp)
This function is called by:
SOURCE CODE
function [C_J_mean,C_J_std,C_S_mean, C_S_std, R_J_mean,R_J_std,R_S_mean,R_S_std] = control_coefficients_distribution(network,solution)
% [C_J_mean,C_J_std,C_S_mean, C_S_std, R_J_mean,R_J_std,R_S_mean,R_S_std] = control_coefficients_distribution(network,solution)
%
% compute the distribution of control coefficients etc in uncertain models
[null_l, K, N0, pinv_N0, independent_metabolites, N1, L] = analyse_N(network.N(find(network.external==0),:));
 [parvalues,parnames,relevant] = mass_action2par(network.kinetics,network.kinetics.used_fwd,network.kinetics.used_bwd);
 C_J_mean = zeros(size(solution.CC.C_J));
 C_J_sqr = C_J_mean;
 C_S_mean = zeros(size(solution.CC.C_S));
 C_S_sqr = C_S_mean;
 R_J_mean = zeros(length(network.actions),length(parnames));
 R_J_sqr = zeros(length(network.actions),length(parnames));
 R_S_mean = zeros(length(network.metabolites),length(parnames));
 R_S_sqr = zeros(length(network.metabolites),length(parnames));
 clear C_J_list C_S_list R_J_list R_S_list
 for it=1:nit
  [epsilon_1,pi_1] = calculate_epsilon(network,solution.S.list(:,it));
  [C_J_list{it}, C_S_list{it}] = control_coefficients(network.N, epsilon_1, network.external, N0, L);
  [R_S_list{it},R_J_list{it}] = response_coefficients(C_S_list{it},epsilon_1,pi_1);
  C_J_mean =  C_J_mean + C_J_list{it};
  C_S_mean =  C_S_mean + C_S_list{it};
  C_J_sqr =   C_J_sqr + C_J_list{it}.^2;
  C_S_sqr =   C_S_sqr + C_S_list{it}.^2;
  R_J_mean =  R_J_mean + R_J_list{it};
  R_S_mean =  R_S_mean + R_S_list{it};
  R_J_sqr =   R_J_sqr + R_J_list{it}.^2;
  R_S_sqr =   R_S_sqr + R_S_list{it}.^2;
 end
 C_J_mean=C_J_mean/nit;
 C_S_mean=C_S_mean/nit;
 C_J_std=sqrt(1/(nit+1)*(C_J_sqr - C_J_mean.^2));
 C_S_std=sqrt(1/(nit+1)*(C_S_sqr - C_S_mean.^2));
 R_J_mean=R_J_mean/nit;
 R_S_mean=R_S_mean/nit;
 R_J_std=sqrt(1/(nit+1)*(R_J_sqr - R_J_mean.^2));
 R_S_std=sqrt(1/(nit+1)*(R_S_sqr - R_S_mean.^2));