Description of control_coefficients_distr
Home > mnt-advanced > mnt_uncertain_parameters > control_coefficients_distr.m
control_coefficients_distr
PURPOSE
[C_J_mean,C_J_std,C_S_mean, C_S_std, R_J_mean,R_J_std,R_S_mean,R_S_std,R_J_Sext_mean,R_J_Sext_std,R_S_Sext_mean,R_S_Sext_std] =
SYNOPSIS
function [C_J_mean,C_J_std,C_S_mean, C_S_std, R_J_mean,R_J_std,R_S_mean,R_S_std,R_J_Sext_mean,R_J_Sext_std,R_S_Sext_mean,R_S_Sext_std] = control_coefficients_distr(network,solution)
DESCRIPTION
 [C_J_mean,C_J_std,C_S_mean, C_S_std, R_J_mean,R_J_std,R_S_mean,R_S_std,R_J_Sext_mean,R_J_Sext_std,R_S_Sext_mean,R_S_Sext_std] =
 control_coefficients_distr(network,solution)
 compute statistics of control and response coefficients
 'solution': Monte-Carlo results from 'stochastic_parameters'
CROSS-REFERENCE INFORMATION
This function calls:
parameters2vector [vector,names,relevant,relevant_reactions,types] = parameters2vector(kinetics,S_ext,S_ext_names,network,split,no_names)
vector2parameters [kinetics,S_ext] = vector2parameters(kinetics,vector,external_ind,network)
analyse_N [ K, L, NR, null_l, pinv_NR, independent_metabolites, N1] = analyse_N(N,external)
control_coefficients [CJ, CS, L_int, NR_int, M, M_adj, indp_among_internal] = control_coefficients(N, Ec, external, used, NR_int, L_int, indp_among_internal,dilution_rate)
elasticities [Ec,Ep,parameters,Ecc,Ecp,Epp,p] = elasticities(network,s,options);
response_coefficients [RS, RJ, RS2, RJ2] = response_coefficients(CS, Ec, Ep, Ecc, Ecp, Epp)
This function is called by:
SOURCE CODE
function [C_J_mean,C_J_std,C_S_mean, C_S_std, R_J_mean,R_J_std,R_S_mean,R_S_std,R_J_Sext_mean,R_J_Sext_std,R_S_Sext_mean,R_S_Sext_std] = control_coefficients_distr(network,solution)
% [C_J_mean,C_J_std,C_S_mean, C_S_std, R_J_mean,R_J_std,R_S_mean,R_S_std,R_J_Sext_mean,R_J_Sext_std,R_S_Sext_mean,R_S_Sext_std] =
% control_coefficients_distr(network,solution)
%
% compute statistics of control and response coefficients
% 'solution': Monte-Carlo results from 'stochastic_parameters'
[K,L,N0,null_l,pinv_N0,independent_metabolites,N1] = analyse_N(network.N(find(network.external==0),:));
Sext = exp(solution.logSext_mean);
Sext_names = network.metabolites(find(network.external));
[parvalues,parnames,relevant] = parameters2vector(network.kinetics,Sext,Sext_names);
nit      = size(solution.MonteCarlo.S.list,2);
n_par    = length(parvalues);
n_Sext   = sum(network.external);
C_J_mean = zeros(size(solution.control_coefficients.C_J));
C_J_sqr  = C_J_mean;
C_S_mean = zeros(size(solution.control_coefficients.C_S));
C_S_sqr  = C_S_mean;
R_J_mean = zeros(length(network.actions),n_par);
R_J_sqr  = zeros(length(network.actions),n_par);
R_S_mean = zeros(length(network.metabolites),n_par);
R_S_sqr  = zeros(length(network.metabolites),n_par);
R_J_Sext_mean = zeros(length(network.actions),n_Sext);
R_J_Sext_sqr  = zeros(length(network.actions),n_Sext);
R_S_Sext_mean = zeros(length(network.metabolites),n_Sext);
R_S_Sext_sqr  = zeros(length(network.metabolites),n_Sext);
for it=1:nit
  nn = network;
  switch network.kinetics.type
    case 'mass-action', nn.kinetics = par2mass_action(parvalues,nn.kinetics.used_fwd,nn.kinetics.used_bwd,0);
    otherwise,   nn.kinetics = vector2parameters(nn.kinetics,parvalues,[]);
  end
  [epsilon_1,pi_1]     = elasticities(nn,solution.MonteCarlo.S.list(:,it));
  [C_J_this, C_S_this] = control_coefficients(network.N, epsilon_1, network.external, [], N0, L);
  [R_S_this,R_J_this]  = response_coefficients(C_S_this,epsilon_1,pi_1);
  pi_Sext_1            = epsilon_1(:,find(network.external));
  [R_S_Sext_this,R_J_Sext_this] = response_coefficients(C_S_this,epsilon_1,pi_Sext_1);
  C_J_mean =  C_J_mean + C_J_this;
  C_S_mean =  C_S_mean + C_S_this;
  C_J_sqr  =  C_J_sqr + C_J_this.^2;
  C_S_sqr  =  C_S_sqr + C_S_this.^2;
  R_J_mean =  R_J_mean + R_J_this;
  R_S_mean =  R_S_mean + R_S_this;
  R_J_sqr  =  R_J_sqr + R_J_this.^2;
  R_S_sqr  =  R_S_sqr + R_S_this.^2;
  R_J_Sext_mean =  R_J_Sext_mean + R_J_Sext_this;
  R_S_Sext_mean =  R_S_Sext_mean + R_S_Sext_this;
  R_J_Sext_sqr  =  R_J_Sext_sqr + R_J_Sext_this.^2;
  R_S_Sext_sqr  =  R_S_Sext_sqr + R_S_Sext_this.^2;
end
C_J_mean = C_J_mean/nit;
C_S_mean = C_S_mean/nit;
C_J_std=sqrt(1/(nit+1)*(C_J_sqr - C_J_mean.^2));
C_S_std=sqrt(1/(nit+1)*(C_S_sqr - C_S_mean.^2));
R_J_mean = R_J_mean/nit;
R_S_mean = R_S_mean/nit;
R_J_std = sqrt(1/(nit+1)*(R_J_sqr - R_J_mean.^2));
R_S_std = sqrt(1/(nit+1)*(R_S_sqr - R_S_mean.^2));
R_J_Sext_mean = R_J_Sext_mean/nit;
R_S_Sext_mean = R_S_Sext_mean/nit;
R_J_Sext_std = sqrt(1/(nit+1)*(R_J_Sext_sqr - R_J_Sext_mean.^2));
R_S_Sext_std = sqrt(1/(nit+1)*(R_S_Sext_sqr - R_S_Sext_mean.^2));