Description of mdf
Home > mnt-basic > mnt_fluxes > mdf > mdf.m
mdf
PURPOSE
[c,A] = mdf(N, v, keq, mdf_options)
SYNOPSIS
function [c, A, feasible] = mdf(N, v, keq, mdf_options, verbose)
DESCRIPTION
 [c,A] = mdf(N, v, keq, mdf_options)
Max-min driving force method
 Bounds and fixed values for metabolites are given in 'mdf_options'
 (for details, see mdf_default_options.m)
 The fluxes are only used to recognise inactive reactions and negative fluxes
 If zero or negative fluxes occur, the problem is internally rewritten into
 a problem with positive fluxes only. The output refers to the original problem.
 Options (in struct 'options'):
   mdf_options.c_min; % concentration vector (mM); nan if not specified
   mdf_options.c_max; % concentration vector (mM); nan if not specified
   mdf_options.c_fix; % concentration vector (mM); nan if not specified
   mdf_options.weight_by_fluxes; flag; during optimisation, weight the forces by flux values
   mdf_options.ind_ignore_reactions; indices of reactions to be ignored in mdf
   mdf_options.log_keq (this is overriden by the function argument keq, if provided)
CROSS-REFERENCE INFORMATION
This function calls:
mdf [c,A] = mdf(N, v, keq, mdf_options)
RT result = RT(temperature)
default commandstring = default(varname1,defaultvalue1,varname2,defaultvalue2,...)
This function is called by:
mdf [c,A] = mdf(N, v, keq, mdf_options)