Description of netgraph_flux_movie
Home > mnt > mnt-basic > mnt_graphics > netgraph_flux_movie.m
netgraph_flux_movie
PURPOSE
M = netgraph_flux_movie(network,S,J,text_flag,goptions);
SYNOPSIS
function M = netgraph_flux_movie(network,S,J,text_flag,goptions);
DESCRIPTION
 M = netgraph_flux_movie(network,S,J,text_flag,goptions);
 Movie showing a single flux distribution (moving arrows only to highlight fluxes)
 S and J : vectors of concentrations and fluxes
 the number of frames can be set by 'n_frames' within goptions
 to save a movie as an animated gif, use movie_save(filename,M)
CROSS-REFERENCE INFORMATION
This function calls:
netgraph_concentrations netgraph_concentrations(network,S,J,flag_text,options)
circle circle(x,y,r,col,filled,linewidth)
default commandstring = default(varname1,defaultvalue1,varname2,defaultvalue2,...)
join_struct a = join_struct(a,b)
This function is called by:
mnt_demo