Description of netgraph_mark_reactions
Home > mnt > mnt-basic > mnt_graphics > netgraph_mark_reactions.m
netgraph_mark_reactions
PURPOSE
[choice,p] = netgraph_mark_reactions(network,choice,draw_only)
SYNOPSIS
function [choice,p] = netgraph_mark_reactions(network,choice,draw_only)
DESCRIPTION
 [choice,p] = netgraph_mark_reactions(network,choice,draw_only)
CROSS-REFERENCE INFORMATION
This function calls:
netgraph_concentrations netgraph_concentrations(network,S,J,flag_text,options)
default commandstring = default(varname1,defaultvalue1,varname2,defaultvalue2,...)
This function is called by:
netgraph_reversible [network,p] = netgraph_reversible(network)