Description of spectral_response_coefficients
Home > mnt > mnt-basic > mnt_mca > spectral_response_coefficients.m
spectral_response_coefficients
PURPOSE
[RS, RJ, RS_2_2omega, RJ_2_2omega, RS_2_2omega0, RJ_2_2omega0, CS,CS_2_omega,CJ,CJ_2_omega] = ...
SYNOPSIS
function [RS_omega,RJ_omega,RS_2_2omega,RJ_2_2omega,RS_2_2omega0,RJ_2_2omega0,CS_omega,CS_2_omega,CJ_omega,CJ_2_omega] = spectral_response_coefficients(N0,L,M0,delta_par,Ec,Ep,Ecc,Ecp,Epp)
DESCRIPTION
[RS, RJ, RS_2_2omega, RJ_2_2omega, RS_2_2omega0, RJ_2_2omega0, CS,CS_2_omega,CJ,CJ_2_omega] = ...
  spectral_response_coefficients(N0, L, M0, delta_par,Ec,Ep,Ecc,Ecp,Epp)
 Calculate spectral (NOT PERIODIC) response coefficients for INTERNAL metabolites
 L                     link matrix for internal metabolites (see network_analyse)
 N0                    reduced stoichiometric matrix (see network_analyse, N_R)
 delta_par             structure with field 'omega': angular frequency
 Ec, Ep, Ecc, Ecp, Epp elasticities of 1st and 2nd order for INTERNAL metabolites
 M0                    Jacobian matrix (optional)
 For instance, RS_2_2omega0 is the coefficient for and output at frequency 0
 and inputs of frequency omega (from the left) and frequency -omega (from the right)
CROSS-REFERENCE INFORMATION
This function calls:
default commandstring = default(varname1,defaultvalue1,varname2,defaultvalue2,...)
tensor_product C = tensor_product(A,B,index_A,index_B)
This function is called by:
osc_resp_plot_timecourses [RS_omega,RV_omega] = osc_resp_plot_timecourses(network,t_appr,x_ss,v_ss,t,x,v,M0,delta_par_struct,epsilon_1,pi_1,epsilon_2,rho_2,pi_2,color,orderx,orderv)
oscillatory_response this is an updated version of osc_resp_plot_timecourse