Description of network_get_kinetics_strings
Home > mnt > mnt_kinetics > network_get_kinetics_strings.m
network_get_kinetics_strings
PURPOSE
SYNOPSIS
function [my_kinetics_strings,my_kinetic_laws] = network_get_kinetics_strings(network)
DESCRIPTION
CROSS-REFERENCE INFORMATION
This function calls:
cs_get_formula r_name reaction name (for naming the parameters)
ms_get_formula formula = ms_get_formula(r_name,mn,sub,pro,act,inh,m_sub,m_pro)
This function is called by:
network_to_sbtab sbtab_document = network_to_sbtab(network, options)