Description of network_reduce_to_active_subnetwork
Home > mnt-basic > mnt_network > network_build_edit > network_reduce_to_active_subnetwork.m
network_reduce_to_active_subnetwork
PURPOSE
if v is a matrix, choose all reactions for which the flux in any of the states
SYNOPSIS
function [network,ind_m,ind_r] = network_reduce_to_active_subnetwork(network,v,epsilon)
DESCRIPTION
 if v is a matrix, choose all reactions for which the flux in any of the states
 is above threshold (threshold epsilon for absolute rate)
CROSS-REFERENCE INFORMATION
This function calls:
network_remove_action [network1,keep,keep_actions] = network_remove_action(network,ind,flag_remove_metabolites)
default commandstring = default(varname1,defaultvalue1,varname2,defaultvalue2,...)
This function is called by:
network_subnetwork_balanced [network_red,v_red,dmu_red,c_red] = network_subnetwork_balanced(network,v,epsilon,vmin,dmu,c)