Description of parameter_balancing_kinetic_metabolic
Home > mnt-advanced > mnt_parameter_balancing > parameter_balancing_kinetic_metabolic.m
parameter_balancing_kinetic_metabolic
PURPOSE
[r, r_orig, kinetic_data, r_samples, parameter_prior, r_mean, r_std,r_geom_mean,r_geom_std] = parameter_balancing_kinetic(network, kinetic_data, file_kinetic_data, pb_options, v);
SYNOPSIS
function [r, r_orig, kinetic_data, r_samples, parameter_prior, r_mean, r_std,r_geom_mean,r_geom_std] = parameter_balancing_kinetic_metabolic(network, kinetic_data, pb_options, v);
DESCRIPTION
  [r, r_orig, kinetic_data, r_samples, parameter_prior, r_mean, r_std,r_geom_mean,r_geom_std] = parameter_balancing_kinetic(network, kinetic_data, file_kinetic_data, pb_options, v);
 Determine consistent kinetic parameter and metabolic state by parameter balancing
 This function resembles parameter_balancing_kinetic. Please see the documentation there.
CROSS-REFERENCE INFORMATION
This function calls:
data_integration_load_kinetic_data kinetic_data = kinetic_data = data_integration_load_kinetic_data(data_quantities, parameter_prior, network, data_file, use_sbml_ids, use_kegg_ids, flag_invent_std, verbose, filter_column, filter_entry, reaction_column_name, compound_column_name)
parameter_balancing_calculation [result, exitflag] = parameter_balancing(task, parameter_prior, options)
parameter_balancing_default_options PARAMETER_BALANCING_DEFAULT_OPTIONS Options for parameter balancing - empty data structure
parameter_balancing_output [r_mode, r_mean, r_std, r_geom_mean, r_geom_std, r_orig,r_samples] = parameter_balancing_output(res,kinetic_data_orig,options)
parameter_balancing_prior parameter_prior = parameter_balancing_prior(omit_quantities,parameter_prior_filename)
parameter_balancing_task [task, prior] = parameter_balancing_task(network, kinetic_data, parameter_prior, model_quantities, basic_quantities,include_metabolic)
pb_kinetic_data_adjust
pb_parameter_prior_adjust
network_velocities v = network_velocities(s,network,kinetics,split,indices,t)
set_kinetics kinetics = set_kinetics(network,type,parameters)
default commandstring = default(varname1,defaultvalue1,varname2,defaultvalue2,...)
join_struct a = join_struct(a,b)
This function is called by:
demo_pb_ecoli_noor_2016 ---------------------------------------------------------------------------------------------