Description of network_numbers
Home > mnt > mnt-basic > mnt_network > network_query > network_numbers.m
network_numbers
PURPOSE
[nr,nm,nx,KM_indices,KA_indices,KI_indices,nKM,nKA,nKI] = network_numbers(network)
SYNOPSIS
function [nr,nm,nx,KM_indices,KA_indices,KI_indices,nKM,nKA,nKI] = network_numbers(network)
DESCRIPTION
[nr,nm,nx,KM_indices,KA_indices,KI_indices,nKM,nKA,nKI] = network_numbers(network)
CROSS-REFERENCE INFORMATION
This function calls:
column transform a vector (row or column) into a column vector
This function is called by:
netgraph_print_positions [names, positions] = netgraph_print_positions(network,layout_file,offsets,policy,flag_KEGG_ids,flag_element_names,flag_fixed,flag_invisible)
convenience_parameter_vector_indices types = convenience_parameter_vector_indices(network,dynamic_flag,n_exp,dependent_flag,nw)
kin_data_construct
modular_kinetic_formulae [formula, global_assignment, local_assignment] = modular_kinetic_formulae(network)
modular_rate_law_to_sbtab quantity_table = modular_rate_law_to_sbtab(network,filename,options)
modular_to_numeric_initialise [numeric_network,numeric_kinetics] = modular_to_numeric_initialise(network,kinetics,dilution);
mrl_kinetics_to_sbtab s = mrl_kinetics_to_sbtab(network, kinetics, parameter_prior, save_quantities, file_basename)
ms_import_kinetic [kin_data,parameter_prior] = ms_import_kinetic(network,kinetic_balanced_file)
modular_par2vector [v,names] = modular_par2vector(p,network,no_names)
sbtab_to_modular_rate_law [kinetics, sbtab_table, other_parameters] = sbtab_to_modular_rate_law(network,file_kinetic_data,options)
sbtab_to_modular_rate_law_via_kinetic_data [kinetics, kinetic_data] = sbtab_to_modular_rate_law(network,file_kinetic_data,options)
ms_vector2par kinetics = ms_vector2par(vector,kinetics,network)
network_add_empty network = network_add_empty(network,a,b);
network_add_metabolites network = network_add_metabolites(network,new_metabolites,new_external);
network_add_reaction network = network_add_reaction(network,reactants,stoich_coeffs,name,reversible);
network_add_transport network = network_add_transport(network, metabolites,flag_only_reactions);
parameter_balancing_calculation [result, exitflag] = parameter_balancing(task, parameter_prior, options)
parameter_balancing_constrained_sampling [q_sample, xmodel_sample, xdata_sample, kinetics_sample, v_sample, q_min, q_max] = parameter_balancing_constrained_sampling(task,res,options,parameter_prior)
parameter_balancing_model_matrices
parameter_balancing_quantity_numbers count how many quantities of a certain type appear in a model
parameter_balancing_sample_models
parameter_balancing_task [task, prior] = parameter_balancing_task(network, kinetic_data, parameter_prior, model_quantities, basic_quantities,include_metabolic)