Description of alpha_to_betagamma
Home > mnt > mnt_kinetics > modular_rate_laws > modular_rate_law_functions > parameter_conversion > alpha_to_betagamma.m
alpha_to_betagamma
PURPOSE
[beta_A, gamma_A] = alpha_to_betagamma(alpha_A)
SYNOPSIS
function [beta_A, gamma_A] = alpha_to_betagamma(alpha_A)
DESCRIPTION
 [beta_A, gamma_A] = alpha_to_betagamma(alpha_A)
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
compute_cs_elasticities E = compute_cs_elasticities(N, W, ext_ind, alpha_A, alpha_I, alpha_M, vplus, vminus, u, c)
compute_ds_elasticities E = compute_ms_elasticities(N, W, ext_ind, alpha_A, alpha_I, alpha_M, vplus, vminus, u, c)
compute_modular_elasticities E = compute_modular_elasticities(kinetic_law, N, W, ind_ext, alpha_A, alpha_I, alpha_M, v, A, u, c, h, v_plus_fallback, v_minus_fallback,flag_second_order)
compute_modular_elasticities_second E_target = compute_modular_elasticities_second(z,kinetic_law,N, W, ind_ext, alpha_A, alpha_I, alpha_M, v, A, u, c, h, v_plus_fallback, v_minus_fallback)
compute_rp_elasticities E = compute_ms_elasticities(N, W, ext_ind, alpha_A, alpha_I, alpha_M, vplus, vminus, u, c)
compute_ms_elasticities E = compute_ms_elasticities(N, W, ext_ind, alpha_A, alpha_I, alpha_M, vplus, vminus, u, c)
SOURCE CODE
function [beta_A, gamma_A] = alpha_to_betagamma(alpha_A)
% [beta_A, gamma_A] = alpha_to_betagamma(alpha_A)
[nr,nm] = size(alpha_A);
beta_A = sparse(nr,nm);
beta_A(find(alpha_A)) = 1-alpha_A(find(alpha_A));
gamma_A = alpha_A .* beta_A;