Description of k_to_log_alpha
Home > mnt > mnt_kinetics > modular_rate_laws > modular_rate_law_functions > parameter_conversion > k_to_log_alpha.m
k_to_log_alpha
PURPOSE
log_alpha_X,log_beta_X: sparse matrices
SYNOPSIS
function [log_alpha_X,log_beta_X] = k_to_log_alpha(KX,c,hill);
DESCRIPTION
 log_alpha_X,log_beta_X: sparse matrices
CROSS-REFERENCE INFORMATION
This function calls:
default commandstring = default(varname1,defaultvalue1,varname2,defaultvalue2,...)
This function is called by:
compute_cs_kX_elasticities [E_kX_sc,kX_names,kX] = compute_cs_kX_elasticities(network, c);
k_to_alpha [alpha_X,beta_X] = k_to_alpha(KX,c,hill);
modular_velocities [v, v_plus, v_minus] = modular_velocities(kinetic_law,N,W,ind_ext,u,c,KA,KI,KM,KV,Keq,h,Mplus, Mminus, Wplus, Wminus, nm, nr)
test_modular_rate_law r = test_moldular_rate_law(n,kinetics)
SOURCE CODE
function [log_alpha_X,log_beta_X] = k_to_log_alpha(KX,c,hill);
% log_alpha_X,log_beta_X: sparse matrices
eval(default('hill','1'));
[nr,nm] = size(KX);
ind_KX  = find(KX);
C                     = repmat(c',nr,1);
log_alpha_X           = sparse(nr,nm);
log_alpha_X(ind_KX)   = - log(1 + [C((ind_KX)) ./ KX(ind_KX)].^hill);
if nargout >1,
  log_beta_X          = sparse(nr,nm);
  log_beta_X(ind_KX)  = log( [C((ind_KX)) ./ KX(ind_KX)].^hill  ) + log_alpha_X(ind_KX);
end