Description of k_to_alpha
Home > mnt > mnt_kinetics > modular_rate_laws > modular_rate_law_functions > parameter_conversion > k_to_alpha.m
k_to_alpha
PURPOSE
[alpha_X,beta_X] = k_to_alpha(KX,c,hill);
SYNOPSIS
function [alpha_X,beta_X] = k_to_alpha(KX,c,hill);
DESCRIPTION
 [alpha_X,beta_X] = k_to_alpha(KX,c,hill);
CROSS-REFERENCE INFORMATION
This function calls:
k_to_log_alpha log_alpha_X,log_beta_X: sparse matrices
default commandstring = default(varname1,defaultvalue1,varname2,defaultvalue2,...)
This function is called by:
test_modular_rate_law r = test_moldular_rate_law(n,kinetics)
SOURCE CODE
function [alpha_X,beta_X] = k_to_alpha(KX,c,hill);
% [alpha_X,beta_X] = k_to_alpha(KX,c,hill);
eval(default('hill','1'));
[nr,nm] = size(KX);
ind_KX  = find(KX);
alpha_X = sparse(nr,nm);
if nargout == 1,
  log_alpha_X = k_to_log_alpha(KX,c,hill);
  alpha_X(ind_KX) = exp(log_alpha_X(ind_KX));
else
  [log_alpha_X,log_beta_X] = k_to_log_alpha(KX,c,hill);
  alpha_X(ind_KX)  = exp(log_alpha_X(ind_KX));
  beta_X           = sparse(nr,nm);
  beta_X(ind_KX)   = exp(log_beta_X(ind_KX));
end