Description of modular_par2vector
Home > mnt > mnt_kinetics > modular_rate_laws > modular_rate_law_functions > parameter_conversion > modular_par2vector.m
modular_par2vector
PURPOSE
[v,names] = modular_par2vector(p,network,no_names)
SYNOPSIS
function [v,names] = modular_par2vector(p,network,no_names)
DESCRIPTION
 [v,names] = modular_par2vector(p,network,no_names)
CROSS-REFERENCE INFORMATION
This function calls:
network_numbers [nr,nm,nx,KM_indices,KA_indices,KI_indices,nKM,nKA,nKI] = network_numbers(network)
column transform a vector (row or column) into a column vector
numbered_names list = numbered_names(name,n_max)
This function is called by:
parameters2vector [vector,names,relevant,relevant_reactions,types] = parameters2vector(kinetics,S_ext,S_ext_names,network,split,no_names)
SOURCE CODE
function [v,names] = modular_par2vector(p,network,no_names)
% [v,names] = modular_par2vector(p,network,no_names)
[nr,nm,nx,KM_indices,KA_indices,KI_indices,nKM,nKA,nKI] = network_numbers(network);
v              = [p.u; p.c; column(p.KA(KA_indices)); column(p.KI(KI_indices)); column(p.KM(KM_indices)); p.KV; p.Keq];
if no_names,
  names =[];
else,
  u_names        = numbered_names('u',nr);
  c_names        = numbered_names('c',nm);
  KA_names       = numbered_names('KA',[nr,nm]);
  KI_names       = numbered_names('KI',[nr,nm]);
  KM_names       = numbered_names('KM',[nr,nm]);
  KV_names       = numbered_names('KV',nr);
  Keq_names      = numbered_names('Keq',nr);
  names          = [u_names;c_names;column(KA_names(KA_indices));column(KI_names(KI_indices));...
                    column(KM_names(KM_indices));KV_names;Keq_names];
end