Description of modular_KV_Keq_to_kcat
Home > mnt > mnt_kinetics > modular_rate_laws > modular_rate_law_functions > parameter_conversion > modular_KV_Keq_to_kcat.m
modular_KV_Keq_to_kcat
PURPOSE
[kcatplus, kcatminus] = modular_kcat_to_KV_Keq(N,kinetics,KV,Keq,KM)
SYNOPSIS
function [kcatplus, kcatminus] = modular_KV_Keq_to_kcat(N,kinetics,KV,Keq,KM,h)
DESCRIPTION
 [kcatplus, kcatminus] = modular_kcat_to_KV_Keq(N,kinetics,KV,Keq,KM)
CROSS-REFERENCE INFORMATION
This function calls:
ms_compute_Kcat [kcatplus,kcatminus] = ms_compute_Kcat(N,KM,KV,Keq);
default commandstring = default(varname1,defaultvalue1,varname2,defaultvalue2,...)
This function is called by:
sbtab_to_modular_rate_law [kinetics, sbtab_table] = sbtab_to_modular_rate_law(network,file_kinetic_data,options)