Description of modular_kcat_to_KV_Keq
Home > mnt > mnt_kinetics > modular_rate_laws > modular_rate_law_functions > parameter_conversion > modular_kcat_to_KV_Keq.m
modular_kcat_to_KV_Keq
PURPOSE
[kinetics,KV,Keq] = modular_kcat_to_KV_Keq(N,kinetics,kcatplus,kcatminus,Keq)
SYNOPSIS
function [kinetics,KV,Keq] = modular_kcat_to_KV_Keq(N,kinetics,kcatplus,kcatminus,Keq)
DESCRIPTION
 [kinetics,KV,Keq] = modular_kcat_to_KV_Keq(N,kinetics,kcatplus,kcatminus,Keq)
CROSS-REFERENCE INFORMATION
This function calls:
default commandstring = default(varname1,defaultvalue1,varname2,defaultvalue2,...)
This function is called by:
modular_kcat_linear_to_KV_Keq [kinetics,KV,Keq] = modular_kcat_linear_to_KV_Keq(N,kinetics,kcat_linear_plus,kcat_linear_minus,Keq)
ms_KM_kcat_to_Keq_KV [Keq,KV] = ms_KM_kcat_to_Keq_KV(N,kinetics,KM,kcatplus,kcatminus);
SOURCE CODE
function [kinetics,KV,Keq] = modular_kcat_to_KV_Keq(N,kinetics,kcatplus,kcatminus,Keq)
% [kinetics,KV,Keq] = modular_kcat_to_KV_Keq(N,kinetics,kcatplus,kcatminus,Keq)
eval(default('kcatminus','[]','Keq','[]'));
all_KM              = ones(size(N'));
all_KM(find(N'~=0)) = kinetics.KM(find(N'~=0));
KMprod              = prod(all_KM.^(N'),2);
if length(kcatminus),
  Keq = kcatplus./kcatminus./KMprod;
end
KV  = sqrt([kcatplus .* kcatminus]);
kinetics.KV  = KV;
kinetics.Keq = Keq;