Description of ms_compute_Kcat
Home > mnt > mnt_kinetics > modular_rate_laws > modular_rate_law_functions > parameter_conversion > ms_compute_Kcat.m
ms_compute_Kcat
PURPOSE
[Kplus,Kminus] = ms_compute_Kcat(N,KM,KV,Keq);
SYNOPSIS
function [Kplus,Kminus] = ms_compute_Kcat(N,KM,KV,Keq);
DESCRIPTION
 [Kplus,Kminus] = ms_compute_Kcat(N,KM,KV,Keq);
CROSS-REFERENCE INFORMATION
This function calls:
ms_compute_log_Kcat [log_Kplus,log_Kminus] = ms_compute_log_Kcat(N,KM,KV,Keq,pars);
This function is called by:
modular_fast_parameters pars = modular_fast_parameters(N,W,ind_ext,KA,KI,KM,KV,Keq,h)
modular_velocities [v, v_plus, v_minus] = modular_velocities(kinetic_law,N,W,ind_ext,u,c,KA,KI,KM,KV,Keq,h,Mplus, Mminus, Wplus, Wminus, nm, nr)
test_modular_rate_law r = test_moldular_rate_law(n,kinetics)
SOURCE CODE
function [Kplus,Kminus] = ms_compute_Kcat(N,KM,KV,Keq);
% [Kplus,Kminus] = ms_compute_Kcat(N,KM,KV,Keq);
[log_Kplus,log_Kminus] = ms_compute_log_Kcat(N,KM,KV,Keq);
Kplus                  = exp(log_Kplus);
Kminus                 = exp(log_Kminus);