Description of ms_KM_kcat_to_Keq_KV
Home > mnt > mnt_kinetics > modular_rate_laws > modular_rate_law_functions > parameter_conversion > ms_KM_kcat_to_Keq_KV.m
ms_KM_kcat_to_Keq_KV
PURPOSE
[Keq,KV] = ms_KM_kcat_to_Keq_KV(N,kinetics,KM,kcatplus,kcatminus);
SYNOPSIS
function [Keq,KV] = ms_KM_kcat_to_Keq_KV(N,kinetics,KM,kcatplus,kcatminus);
DESCRIPTION
 [Keq,KV] = ms_KM_kcat_to_Keq_KV(N,kinetics,KM,kcatplus,kcatminus);
CROSS-REFERENCE INFORMATION
This function calls:
modular_kcat_to_KV_Keq [kinetics,KV,Keq] = modular_kcat_to_KV_Keq(N,kinetics,kcatplus,kcatminus,Keq)
ms_KM_KVratio_to_Keq keq = ms_KM_KVratio_to_Keq(N,KM,KVratio);
This function is called by:
parameter_balancing_sample_models