Description of ms_KM_KVratio_to_Keq
Home > mnt > mnt_kinetics > modular_rate_laws > modular_rate_law_functions > parameter_conversion > ms_KM_KVratio_to_Keq.m
ms_KM_KVratio_to_Keq
PURPOSE
keq = ms_KM_KVratio_to_Keq(N,KM,KVratio);
SYNOPSIS
function keq = ms_KM_KVratio_to_Keq(N,KM,KVratio);
DESCRIPTION
 keq = ms_KM_KVratio_to_Keq(N,KM,KVratio);
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
modular_kinetic_formulae [formula, global_assignment, local_assignment] = modular_kinetic_formulae(network)
mrl_kinetics_to_sbtab s = mrl_kinetics_to_sbtab(network, kinetics, quantity_info, save_quantities, file_basename)
ms_KM_kcat_to_Keq_KV [Keq,KV] = ms_KM_kcat_to_Keq_KV(N,kinetics,KM,kcatplus,kcatminus);
network_sbml_export SBMLmodel = network_sbml_export(network, verbose, name, filename, notes, sbml_level, sbml_version)
SOURCE CODE
function keq = ms_KM_KVratio_to_Keq(N,KM,KVratio);
% keq = ms_KM_KVratio_to_Keq(N,KM,KVratio);
all_KM              = ones(size(N'));
all_KM(find(N'~=0)) = KM(find(N'~=0));
keq                 = KVratio .* prod(all_KM.^(N'),2);