Description of thermo_pb
Home > mnt > mnt-basic > mnt_thermodynamics > thermo_pb.m
thermo_pb
PURPOSE
[c,A] = thermo_pb(N, v, thermo_pb_options, verbose)
SYNOPSIS
function [c, dG0, A, feasible] = thermo_pb(N, v, thermo_pb_options, verbose)
DESCRIPTION
 [c,A] = thermo_pb(N, v, thermo_pb_options, verbose)
 Thermodynamic parameter balancing (uses stoichiometric matrix as an input)
 This function is independent of the general parameter balancing functions
 (the formulae for thermodynamic parameter balancing problem are explictly solved)
 (for an alternative function that imports all model data in a data structure,
  see 'parameter_balancing_thermodynamic')
 All quantitative information (bounds and fixed values for metabolites)
 is given in function argument 'thermo_pb_options'.
 The fluxes are only used to recognise inactive reactions and negative fluxes.
 If vanishing or negative fluxes occur, the problem is converted into a problem
 with positive fluxes. The output, however, refers to the original problem again.
 Options (in struct 'options'):
   thermo_pb_options.c_min; % concentration vector (mM); nan if not specified
   thermo_pb_options.c_max; % concentration vector (mM); nan if not specified
   thermo_pb_options.c_fix; % concentration vector (mM); nan if not specified
   thermo_pb_options.ind_ignore_reactions; indices of reactions to be ignored
   thermo_pb_options.delta_G0  (referring to standard concentration 1mM)
   thermo_pb_options.delta_G0_std
   thermo_pb_options.log_c (natural log of concentration in mM)
   thermo_pb_options.log_c_std
CROSS-REFERENCE INFORMATION
This function calls:
RT result = RT(temperature)
thermo_pb [c,A] = thermo_pb(N, v, thermo_pb_options, verbose)
default commandstring = default(varname1,defaultvalue1,varname2,defaultvalue2,...)
This function is called by:
thermo_pb [c,A] = thermo_pb(N, v, thermo_pb_options, verbose)