Description of mdf_default_options
Home > mnt > mnt-basic > mnt_fluxes > mdf > mdf_default_options.m
mdf_default_options
PURPOSE
mdf_options = mdf_default_options(network,opt)
SYNOPSIS
function mdf_options = mdf_default_options(network,opt)
DESCRIPTION
 mdf_options = mdf_default_options(network,opt)
 Options and default values (concentrations are in mM):
 mdf_options.c_min = nan * ones(nm,1);
 mdf_options.c_max = nan * ones(nm,1);
 mdf_options.c_fix = nan * ones(nm,1);
 mdf_options.ind_ignore_reactions = [];
 where nm = # metabolites (rows of full stoichiometric matrix N)
 fixed metabolite concentrations can be supplied by a structure opt.fixed_met
 with elements opt.fixed_met.[METABOLITE_NAME] == [METABOLITE_VALUE]
CROSS-REFERENCE INFORMATION
This function calls:
default commandstring = default(varname1,defaultvalue1,varname2,defaultvalue2,...)
join_struct a = join_struct(a,b)
label_names function [label,indices] = label_names(names,allnames, method)
This function is called by: