Description of set_cs_kinetics
Home > mnt > mnt_kinetics > modular_rate_laws > cs_rate_law > set_cs_kinetics.m
set_cs_kinetics
PURPOSE
kinetics = set_cs_kinetics(network,parameters)
SYNOPSIS
function kinetics = set_cs_kinetics(network,parameters)
DESCRIPTION
 kinetics = set_cs_kinetics(network,parameters)
 parameters: see set_ms_kinetics
CROSS-REFERENCE INFORMATION
This function calls:
set_ms_kinetics kinetics = set_ms_kinetics(network,parameters)
default commandstring = default(varname1,defaultvalue1,varname2,defaultvalue2,...)
This function is called by:
set_kinetics kinetics = set_kinetics(network,type,parameters)
set_modular_kinetics kinetics = set_modular_kinetics(network,kinetic_law);
parameter_balancing_sample_models
SOURCE CODE
function kinetics = set_cs_kinetics(network,parameters)
% kinetics = set_cs_kinetics(network,parameters)
%
% parameters: see set_ms_kinetics
eval(default('parameters','struct'));
kinetics = set_ms_kinetics(network,parameters);
kinetics.type = 'cs';