Description of set_modular_kinetics
Home > mnt > mnt_kinetics > modular_rate_laws > modular_rate_law_functions > set_modular_kinetics.m
set_modular_kinetics
PURPOSE
kinetics = set_modular_kinetics(network,kinetic_law);
SYNOPSIS
function kinetics = set_modular_kinetics(network,kinetic_law);
DESCRIPTION
 kinetics = set_modular_kinetics(network,kinetic_law);
CROSS-REFERENCE INFORMATION
This function calls:
set_cs_kinetics kinetics = set_cs_kinetics(network,parameters)
set_ds_kinetics kinetics = set_ds_kinetics(network,parameters)
set_ms_kinetics kinetics = set_ms_kinetics(network,parameters)
set_rp_kinetics kinetics = set_rp_kinetics(network,parameters)
This function is called by:
SOURCE CODE
function kinetics = set_modular_kinetics(network,kinetic_law);
% kinetics = set_modular_kinetics(network,kinetic_law);
switch kinetic_law,
  case 'cs', kinetics = set_cs_kinetics(network);
  case 'ds', kinetics = set_ds_kinetics(network);
  case 'ms', kinetics = set_ms_kinetics(network);
  case 'rp', kinetics = set_rp_kinetics(network);
  case 'fd', kinetics = set_fd_kinetics(network);
end