Description of set_ds_kinetics
Home > mnt > mnt_kinetics > modular_rate_laws > ds_rate_law > set_ds_kinetics.m
set_ds_kinetics
PURPOSE
kinetics = set_ds_kinetics(network,parameters)
SYNOPSIS
function kinetics = set_ds_kinetics(network,parameters)
DESCRIPTION
 kinetics = set_ds_kinetics(network,parameters)
CROSS-REFERENCE INFORMATION
This function calls:
set_ms_kinetics kinetics = set_ms_kinetics(network,parameters)
This function is called by:
set_kinetics kinetics = set_kinetics(network,type,parameters)
set_modular_kinetics kinetics = set_modular_kinetics(network,kinetic_law);
SOURCE CODE
function kinetics = set_ds_kinetics(network,parameters)
% kinetics = set_ds_kinetics(network,parameters)
if exist('parameters','var'),
  kinetics      = set_ms_kinetics(network,parameters);
else,
  kinetics = set_ms_kinetics(network);
end
kinetics.type = 'ds';