Description of demo_pb_sbtab
Home > mnt-advanced > mnt_parameter_balancing > demo > demo_pb_sbtab.m
demo_pb_sbtab
PURPOSE
-------------------------------------------------------------------------
SYNOPSIS
This is a script file.
DESCRIPTION
 -------------------------------------------------------------------------
 Demo script: usage examples for matlab function parameter_balancing_sbtab
 -------------------------------------------------------------------------
CROSS-REFERENCE INFORMATION
This function calls:
pb_example_files [model_file, data_file, prior_file, config_file] = pb_example_files(test_example);
parameter_balancing_check ECM_CHECK_PARAMETER_BALANCING - Checks for balanced parameters
parameter_balancing_sbtab [network, r, r_orig, kinetic_data, r_samples, parameter_prior, r_mean, r_std] = parameter_balancing_sbtab(model_file, data_file, pb_options)
modular_rate_law_to_sbtab quantity_table = modular_rate_law_to_sbtab(network,filename,options)
mytable result = mytable(names,rownumbers,filename)
This function is called by: