Description of data_integration_load_quantity_info
Home > mnt > mnt_data_integration > data_integration_load_quantity_info.m
data_integration_load_quantity_info
PURPOSE
quantity_info = data_integration_load_quantity_info(omit_quantities,quantity_info_filename)
SYNOPSIS
function quantity_info = data_integration_load_quantity_info(omit_quantities,quantity_info_filename)
DESCRIPTION
 quantity_info = data_integration_load_quantity_info(omit_quantities,quantity_info_filename)
CROSS-REFERENCE INFORMATION
This function calls:
default commandstring = default(varname1,defaultvalue1,varname2,defaultvalue2,...)
label_names function [label,indices] = label_names(names,allnames, method)
This function is called by:
data_integration_display_kinetic_data T = data_integration_display_kinetic_data(kinetic_data,network,flag_display)
data_integration_load_kinetic_data kinetic_data = data_integration_load_kinetic_data(data_quantities, quantity_info, network, file_kinetic_data, use_sbml_ids, use_kegg_ids, flag_invent_std, verbose)
sbtab_to_modular_rate_law [kinetics, kinetic_data] = sbtab_to_modular_rate_law(network,file_kinetic_data,options)
parameter_balancing [res, exitflag] = parameter_balancing(task, quantity_info, options)
parameter_balancing_sbtab a wrapper for parameter balancing that reads all input data (model, priors, kinetic and metabolic data)
parameter_balancing_task Prepare vectors and matrices for parameter balancing
parameter_balancing_thermodynamic [c, v, mu0, Keq, A, my_kinetic_data] = parameter_balancing_theromdynamic(network, v, filename,options)
parameter_balancing_Keq [Keq, mu0, c, my_kinetic_data] = parameter_balancing_Keq(network, filename,options)
parameter_balancing_kinetic [r,r_orig,kinetic_data] = parameter_balancing_kinetic(network, kinetic_data, filename, Keq_given);
SOURCE CODE
function quantity_info = data_integration_load_quantity_info(omit_quantities,quantity_info_filename)
% quantity_info = data_integration_load_quantity_info(omit_quantities,quantity_info_filename)
if ~exist('sbtab_version','file'),
  error('For this function, the SBtab toolbox must be installed');
end
eval(default('omit_quantities','[]','quantity_info_filename','[]'));
if isempty(quantity_info_filename),
 data_integration_dir = [fileparts(which(mfilename))];
 quantity_info_filename = [ data_integration_dir '/quantity_info.tsv'];
end
quantity_info_sbtab = sbtab_table_load(quantity_info_filename);
quantity_info       = sbtab_table_get_all_columns(quantity_info_sbtab);
keep = 1:length(quantity_info.QuantityType);
if length(omit_quantities),
  keep = setdiff(keep,label_names(omit_quantities,quantity_info.QuantityType));
end
fn = fieldnames(quantity_info);
for it = 1:length(fn),
  quantity_info.(fn{it}) =   quantity_info.(fn{it})(keep);
end
for it = 1:length(quantity_info.Symbol),
  quantity_info.symbol_index.(quantity_info.Symbol{it})=it;
end