Description of basic_control_analysis
Home > mnt > mnt_mca > basic_control_analysis.m
basic_control_analysis
PURPOSE
R = basic_control_analysis(network,s,options)
SYNOPSIS
function R = basic_control_analysis(network,s,options)
DESCRIPTION
 R = basic_control_analysis(network,s,options)
 compute some standard control properties (in fields of R)
 - Fluxes J
 - non-normalised elasticity matrices: epsilon_1, pi_1
 - non-normalised control coefficients: CS CJ
 - non-normalised response coefficients: RS RJ
 -     normalised response coefficients: RS_norm RJ_norm
 options.split (Boolean) split reactions into forward and backward part?
 parameter values and names are listed in 'parameter_values' and 'parameters'
CROSS-REFERENCE INFORMATION
This function calls:
network_get_parameter_values [parameter_values,names,types] = network_get_parameter_values(network,s,only_enzyme_levels)
network_velocities v = network_velocities(s,network,kinetics,split,indices,t)
control_coefficients [CJ, CS, L_int, NR_int, M, M_adj, indp_among_internal] = control_coefficients(N, Ec, external, used, NR_int, L_int, indp_among_internal,dilution_rate)
elasticities [Ec,Ep,parameters,Ecc,Ecp,Epp,p] = elasticities(network,s,options);
response_coefficients [RS, RJ, RS2, RJ2] = response_coefficients(CS, Ec, Ep, Ecc, Ecp, Epp)
network_steady_state [S, J, Sdot, error] = network_steady_state(network,s,integrate_time,L_int,NR_int,indep_met_int,dilution_rate)
default commandstring = default(varname1,defaultvalue1,varname2,defaultvalue2,...)
join_struct c = join_struct(a,b)
This function is called by:
SOURCE CODE
% R = basic_control_analysis(network,s,options)
%
% compute some standard control properties (in fields of R)
%
% - Fluxes J
% - non-normalised elasticity matrices: epsilon_1, pi_1
% - non-normalised control coefficients: CS CJ
% - non-normalised response coefficients: RS RJ
% -     normalised response coefficients: RS_norm RJ_norm
%
% options.split (Boolean) split reactions into forward and backward part?
%
% parameter values and names are listed in 'parameter_values' and 'parameters'
function R = basic_control_analysis(network,s,options)
eval(default('options','struct'));
options_default = struct('split',0,'only_enzyme_levels',1,'dilution_rate',[]);
options         = join_struct(options_default,options);
if isfield(options,'used'),
  used = options.used;
else,
  switch network.kinetics.type,
    case {'cs','ms'},   used = real(network.kinetics.u>0);
    otherwise,  used = [];
  end
end
[R.s,R.j] = network_steady_state(network,s,10000,[],[],[], options.dilution_rate);
R.s = real(R.s);
if find(R.s<0),
  warning('Negative concentrations encountered; replacing them by small values.');  R.s(R.s<0) = 10^-10;
end
[R.parameter_values,R.parameters,R.parameter_types] = network_get_parameter_values(network,s,options.only_enzyme_levels);
[R.epsilon_1,R.pi_1]           = elasticities(network,R.s,options);
[R.CJ, R.CS, L, NR , R.M]      = control_coefficients(network.N, R.epsilon_1,network.external,used);
[R.RS,R.RJ]                    = response_coefficients(R.CS,R.epsilon_1,R.pi_1);
R.RS(find(network.external),:) = 0;
n_ext = sum(network.external);
switch(network.kinetics.type),
  case 'convenience',
    R.RS(find(network.external),end-length(network.metabolites)+find(network.external)) = eye(n_ext);
  otherwise,
    R.RS(find(network.external),end-n_ext+1:end) = eye(n_ext);
end
R.RS_norm = [];
R.RJ_norm = [];
if sum(R.s==0),
  warning('Attempt to normalise by vanishing concentration value');
else,
  R.RS_norm = diag(1./R.s) * R.RS * diag(R.parameter_values);
end
if sum(R.j==0),
  warning('Attempt to normalise by vanishing flux value');
else,
  R.RJ_norm = diag(1./R.j) * R.RJ * diag(R.parameter_values);
end
if options.split,
  R.j_split                        = network_velocities(s,network,network.kinetics, 1);
  [R.epsilon_1_split,R.pi_1_split] = elasticities(network,s,1);
  [R.CJ_split, R.CS_split ]        = control_coefficients([network.N, -network.N], R.epsilon_1_split,network.external);
  [dummy,R.RJ_split]               = response_coefficients(R.CS_split,R.epsilon_1_split,R.pi_1_split);
  R.RJ_split_norm                  = diag(1./R.j_split)*R.RJ_split*diag(R.parameter_values);
end