Description of expand_by_R
Home > mnt > mnt_mca > expand_by_R.m
expand_by_R
PURPOSE
delta_y = expand_by_R(RY_1, RY_2, delta_par);
SYNOPSIS
function delta_y = expand_by_R(RY_1,RY_2,delta_par);
DESCRIPTION
 delta_y = expand_by_R(RY_1, RY_2, delta_par);
 Expand steady-state quantity y using the response coefficients
 delta_par: column vector of parameter differences
CROSS-REFERENCE INFORMATION
This function calls:
tensor_product C = tensor_product(A,B,index_A,index_B)
This function is called by:
check_response_coefficients check_response_coefficients(network,S,J,R_S,R_J,R_S_2,R_J_2,R_S_norm,R_J_norm,R_S_2_norm,R_J_2_norm,sigma_k,par,used)
stochastic_simulations MonteCarlo = stochastic_simulations(nit,n_boot,verbose,network,S,J,par,R_S,R_J,R_S_2,R_J_2,R_S_norm,R_J_norm,R_S_2_norm,R_J_2_norm,distribution, comment,relevant)
SOURCE CODE
% delta_y = expand_by_R(RY_1, RY_2, delta_par);
%
% Expand steady-state quantity y using the response coefficients
%
% delta_par: column vector of parameter differences
function delta_y = expand_by_R(RY_1,RY_2,delta_par);
delta_y = RY_1 * delta_par + 0.5 * tensor_product(RY_2,delta_par) * delta_par;