Description of reduce_N
Home > mnt > mnt_mca > reduce_N.m
reduce_N
PURPOSE
[L, NR,independent_metabolites, N1, dependent_metabolites ] = reduce_N(N)
SYNOPSIS
function [L, NR, independent_metabolites, N1,dependent_metabolites] = reduce_N(N)
DESCRIPTION
 [L, NR,independent_metabolites, N1, dependent_metabolites ] = reduce_N(N)
 compute reduced stoichiometric matrix NR for independent metabolites
 and link matrix L fulfilling L*NR = N
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
analyse_N [ K, L, NR, null_l, pinv_NR, independent_metabolites, N1] = analyse_N(N,external)
control_coefficients [CJ, CS, L_int, NR_int, M, indp_among_internal] = control_coefficients(N, Ec, external, used, NR_int, L_int, indp_among_internal,dilution_rate)
flux_control_coefficients_split [C_J, C_S, L, NR ] = control_coefficients(N, epsilon, ext, used, NR, L, J)
time_response_coefficients [t, s, RS, s_ind, RS_ind, parameters, par_names]= time_response_coefficients(network, s0, t_final)
network_steady_state [S, J, Sdot, error] = network_steady_state(network,s,integrate_time,L_int,NR_int,indep_met_int,dilution_rate)
SOURCE CODE
% [L, NR,independent_metabolites, N1, dependent_metabolites ] = reduce_N(N)
%
% compute reduced stoichiometric matrix NR for independent metabolites
% and link matrix L fulfilling L*NR = N
function [L, NR, independent_metabolites, N1,dependent_metabolites] = reduce_N(N)
[n_metab, n_react] = size(N);
[echelon,independent_metabolites] = rref(N');
NR                                = N(independent_metabolites,:);
L                                 = echelon(1:length(independent_metabolites),:)';
dependent_metabolites = setdiff(1:size(N,1),independent_metabolites);
N1                    = N(dependent_metabolites,:);
L=sparse(L);