Description of response_coefficients
Home > mnt > mnt_mca > response_coefficients.m
response_coefficients
PURPOSE
[RS, RJ, RS2, RJ2] = response_coefficients(CS, Ec, Ep, Ecc, Ecp, Epp)
SYNOPSIS
function [RS,RJ,RS2,RJ2] = response_coefficients(CS,Ec,Ep,Ecc,Ecp,Epp,split)
DESCRIPTION
[RS, RJ, RS2, RJ2] = response_coefficients(CS, Ec, Ep, Ecc, Ecp, Epp)
 Static response coefficients (first and second order)
CROSS-REFERENCE INFORMATION
This function calls:
tensor_product C = tensor_product(A,B,index_A,index_B)
This function is called by:
control_coefficients_distr [C_J_mean,C_J_std,C_S_mean, C_S_std, R_J_mean,R_J_std,R_S_mean,R_S_std,R_J_Sext_mean,R_J_Sext_std,R_S_Sext_mean,R_S_Sext_std] =
control_coefficients_distribution [C_J_mean,C_J_std,C_S_mean, C_S_std, R_J_mean,R_J_std,R_S_mean,R_S_std] = control_coefficients_distribution(network,solution)
basic_control_analysis R = basic_control_analysis(network,s,options)