Description of second_derivative_unscaled2scaled
Home > mnt > mnt_mca > second_derivative_unscaled2scaled.m
second_derivative_unscaled2scaled
PURPOSE
D2_sc = second_derivative_unscaled2scaled(D2_un,D_un,f,x)
SYNOPSIS
function D2_sc = second_derivative_unscaled2scaled(D2_un,D_un,f,x)
DESCRIPTION
 D2_sc = second_derivative_unscaled2scaled(D2_un,D_un,f,x)
 let  D_un be the matrix of unscaled derivatives d f_r / d x_i
 and D2_un be the tensor of unscaled second derivatives d^2 f_r / dx_i dx_j
 compute D2_sc, the tensor of scaled second derivatives d^2 ln f_r / dln x_i dln x_j
CROSS-REFERENCE INFORMATION
This function calls:
tensor_scale U = tensor_scale(T,k,x);
This function is called by:
compute_cs_elasticities E = compute_cs_elasticities(N, W, ext_ind, alpha_A, alpha_I, alpha_M, vplus, vminus, u, c)
compute_ds_elasticities E = compute_ms_elasticities(N, W, ext_ind, alpha_A, alpha_I, alpha_M, vplus, vminus, u, c)
compute_ms_elasticities E = compute_ms_elasticities(N, W, ext_ind, alpha_A, alpha_I, alpha_M, vplus, vminus, u, c)
compute_rp_elasticities E = compute_ms_elasticities(N, W, ext_ind, alpha_A, alpha_I, alpha_M, vplus, vminus, u, c)
scale_elasticities E_sc = scale_elasticities(E,v,c,p)
SOURCE CODE
function D2_sc = second_derivative_unscaled2scaled(D2_un,D_un,f,x)
% D2_sc = second_derivative_unscaled2scaled(D2_un,D_un,f,x)
%
% let  D_un be the matrix of unscaled derivatives d f_r / d x_i
% and D2_un be the tensor of unscaled second derivatives d^2 f_r / dx_i dx_j
% compute D2_sc, the tensor of scaled second derivatives d^2 ln f_r / dln x_i dln x_j
nr = length(f);
dd = [];
for it = 1:nr,
 dd(it,:,:) = - 1/f(it) * D_un(it,:)' * D_un(it,:) + diag(D_un(it,:)' ./ x);
end
D2_sc = tensor_scale(D2_un + dd,1,1./f);
D2_sc = tensor_scale(D2_sc,2,x);
D2_sc = tensor_scale(D2_sc,3,x);