Description of parameter_balancing_options
Home > mnt > mnt-extensions > mnt_parameter_balancing > parameter_balancing_options.m
parameter_balancing_options
PURPOSE
PARAMETER_BALANCING_OPTIONS Options for parameter balancing - Data structure with default values
SYNOPSIS
function options = parameter_balancing_options()
DESCRIPTION
 PARAMETER_BALANCING_OPTIONS Options for parameter balancing - Data structure with default values
 options = parameter_balancing_options()
 General options
   options.parameter_prior_file         = [];                        default prior file (see parameter_balancing_prior.m)
   options.kinetics                     = 'cs';                      kinetics for SBML output model (default common modular rate law)
   options.parametrisation              = 'catalytic rate constant'; type of model parameterisation
   options.reaction_units               = 'concentration per time';  physical unit. alternative: 'amount per time'
   options.GFE_fixed                    = 0                          fixed GFE values
   options.insert_pseudo_values         = 0;                         replace missing data values by pseudo values
   options.use_bounds_from_prior_table  = 1;                         flag: use bounds
   options.include_metabolic            = 1;                         flag: consider concentrations in parameter balancing
   options.enzymes_explicit             = 1;                         flag: disregard maximal velocities in parameter balancing
   options.enforce_flux_directions      = 0;                         flag: set constraints to realise predefined flux directions
   options.adjust_to_fluxes             = 0;                         flag: apply postprocessing to yield predefined fluxes (see parameter_balancing_output)
   options.v                            = [];                        flux vector used by options "enforce_flux_directions" and "adjust_to_fluxes"
   options.ignore_all_constraints       = 0;                         flag: run parameter balancing without constraints
   options.n_samples                    = 0;                         0: no sampling; n>1: generate n sampled parameter sets
   options.preferred_data_element_ids   = 'id';                      data columns to be used for mapping (default: "Reaction" or "Compound") % alternatives 'sbml', 'kegg'
   options.use_sbml_ids                 = 0;                           (redundant with preferred_data_element_ids; field used internally)
   options.use_kegg_ids                 = 0;                           (redundant preferred_data_element_ids; field used internally)
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
demo_pb_ecoli_noor_2016 ---------------------------------------------------------------------------------------------
demo_pb_ecoli_wortel_2018 -----------------------------------------------------------------------------------------
parameter_balancing PARAMETER_BALANCING Read model from SBML file; read data and general options from SBtab files; write results to output files
parameter_balancing_calculation [result, exitflag] = parameter_balancing(task, parameter_prior, options)
parameter_balancing_quantities [model_quantities, basic_quantities, data_quantities, pseudo_quantities] = parameter_balancing_relevant_quantities(parameter_prior,network,options)
parameter_balancing_update_options
parameter_balancing_kinetic PARAMETER_BALANCING_KINETIC Determine a consistent kinetic parameter set
parameter_balancing_sbtab PARAMETER_BALANCING_SBTAB - Wrapper function for parameter balancing
parameter_balancing_thermodynamic PARAMETER_BALANCING_THERMODYNAMIC Thermodynamic parameter balancing