Description of parameter_balancing_update_options
Home > mnt > mnt-extensions > mnt_parameter_balancing > parameter_balancing > parameter_balancing_update_options.m
parameter_balancing_update_options
PURPOSE
SYNOPSIS
function pb_options = parameter_balancing_update_options(pb_options)
DESCRIPTION
CROSS-REFERENCE INFORMATION
This function calls:
join_struct a = join_struct(a,b)
parameter_balancing_options PARAMETER_BALANCING_OPTIONS Options for parameter balancing - Data structure with default values
This function is called by:
parameter_balancing_kinetic PARAMETER_BALANCING_KINETIC Determine a consistent kinetic parameter set
parameter_balancing_sbtab PARAMETER_BALANCING_SBTAB - Wrapper function for parameter balancing
parameter_balancing_thermodynamic PARAMETER_BALANCING_THERMODYNAMIC Thermodynamic parameter balancing