Description of parameter_balancing_output
Home > mnt > mnt-extensions > mnt_parameter_balancing > parameter_balancing > parameter_balancing_output.m
parameter_balancing_output
PURPOSE
[r_mode, r_mean, r_std, r_geom_mean, r_geom_std, r_orig, r_samples, r_flux_adjusted, r_flux_adjusted_std] = parameter_balancing_output(res,kinetic_data_orig,options)
SYNOPSIS
function [r_mode, r_mean, r_std, r_geom_mean, r_geom_std, r_orig, r_samples, r_flux_adjusted, r_flux_adjusted_std] = parameter_balancing_output(res, kinetic_data_orig, options)
DESCRIPTION
 [r_mode, r_mean, r_std, r_geom_mean, r_geom_std, r_orig, r_samples, r_flux_adjusted, r_flux_adjusted_std]  = parameter_balancing_output(res,kinetic_data_orig,options)
 Convert parameter sets, previously obtained by parameter balancing, into the format
 used to describe kinetic parameters in the Metabolic Network Toolbox.
 If option "adjust_to_fluxes" is set, the resulting parameter set (constrained posterior mode)
 is additionally adjusted to yield the predefined flux distribution (vector given in options.v)
CROSS-REFERENCE INFORMATION
This function calls:
network_velocities v = network_velocities(s,network,kinetics,split,indices,t)
RT result = RT(temperature)
default commandstring = default(varname1,defaultvalue1,varname2,defaultvalue2,...)
This function is called by:
parameter_balancing_kinetic PARAMETER_BALANCING_KINETIC Determine a consistent kinetic parameter set
parameter_balancing_sbtab PARAMETER_BALANCING_SBTAB - Wrapper function for parameter balancing
parameter_balancing_thermodynamic PARAMETER_BALANCING_THERMODYNAMIC Thermodynamic parameter balancing