Description of parameter_balancing_check
Home > mnt > mnt-extensions > mnt_parameter_balancing > parameter_balancing > parameter_balancing_check.m
parameter_balancing_check
PURPOSE
ECM_CHECK_PARAMETER_BALANCING - Checks for balanced parameters
SYNOPSIS
function parameter_balancing_check(r, r_orig, network, parameter_prior, show_graphics, show_concentrations)
DESCRIPTION
 ECM_CHECK_PARAMETER_BALANCING - Checks for balanced parameters
 parameter_balancing_check(r, r_orig, network, parameter_prior, show_graphics, show_concentrations)
CROSS-REFERENCE INFORMATION
This function calls:
cell_string2num N = cell_string2num(C)
default commandstring = default(varname1,defaultvalue1,varname2,defaultvalue2,...)
label_names function [label,indices] = label_names(names,allnames, method)
mytable result = mytable(names,rownumbers,filename)
subplot_n
This function is called by:
demo_pb_ecoli_noor_2016 ---------------------------------------------------------------------------------------------
demo_pb_ecoli_wortel_2018 -----------------------------------------------------------------------------------------
parameter_balancing PARAMETER_BALANCING Read model from SBML file; read data and general options from SBtab files; write results to output files