Description of parameter_balancing_calculation
Home > mnt > mnt-extensions > mnt_parameter_balancing > parameter_balancing > parameter_balancing_calculation.m
parameter_balancing_calculation
PURPOSE
[result, exitflag] = parameter_balancing(task, parameter_prior, options)
SYNOPSIS
function [result, exitflag] = parameter_balancing_calculation(task, parameter_prior, options)
DESCRIPTION
 [result, exitflag] = parameter_balancing(task, parameter_prior, options)
 Parameter balancing based on vectors and matrices in data structure 'task'
 Function inputs (mandatory)
  task:  parameter balancing task (see parameter_balancing_task.m)
 Function inputs (optional)
  parameter_prior: table of biochemical quantities (see biochemical_parameter_prior.m)
  options:       options table with fields
                   options.use_pseudo_values (default 0)
                   options.n_samples            (default 0)
                     number of random samples from posterior
                     for output result.kinetics_posterior_samples
                   options.use_bounds_from_prior_table
                   options.fix_Keq_in_sampling
CROSS-REFERENCE INFORMATION
This function calls:
network_numbers [nr,nm,nx,KM_indices,KA_indices,KI_indices,nKM,nKA,nKI] = network_numbers(network)
default commandstring = default(varname1,defaultvalue1,varname2,defaultvalue2,...)
join_struct a = join_struct(a,b)
lognormal_log2normal [mu,sigma] = lognormal_log2normal(mu_log,sigma_log,convention)
parameter_balancing_quantity_numbers count how many quantities of a certain type appear in a model
parameter_balancing_options PARAMETER_BALANCING_OPTIONS Options for parameter balancing - Data structure with default values
This function is called by:
parameter_balancing_kinetic PARAMETER_BALANCING_KINETIC Determine a consistent kinetic parameter set
parameter_balancing_sbtab PARAMETER_BALANCING_SBTAB - Wrapper function for parameter balancing
parameter_balancing_thermodynamic PARAMETER_BALANCING_THERMODYNAMIC Thermodynamic parameter balancing