Description of parameter_balancing_prior
Home > mnt > mnt-extensions > mnt_parameter_balancing > parameter_balancing > parameter_balancing_prior.m
parameter_balancing_prior
PURPOSE
parameter_prior = parameter_balancing_prior(omit_quantities,parameter_prior_filename)
SYNOPSIS
function [parameter_prior, parameter_prior_filename] = parameter_balancing_prior(omit_quantities, parameter_prior_filename, verbose)
DESCRIPTION
 parameter_prior = parameter_balancing_prior(omit_quantities,parameter_prior_filename)
CROSS-REFERENCE INFORMATION
This function calls:
cell_string2num N = cell_string2num(C)
default commandstring = default(varname1,defaultvalue1,varname2,defaultvalue2,...)
label_names function [label,indices] = label_names(names,allnames, method)
num2cellstr
This function is called by:
data_integration_display_kinetic_data T = data_integration_display_kinetic_data(kinetic_data,network,flag_display)
data_integration_load_kinetic_data kinetic_data = data_integration_load_kinetic_data(data_quantities, parameter_prior, network, data_file, options)
parameter_balancing_task [task, prior] = parameter_balancing_task(network, kinetic_data, parameter_prior, model_quantities, basic_quantities,include_metabolic)
parameter_balancing_kinetic PARAMETER_BALANCING_KINETIC Determine a consistent kinetic parameter set
parameter_balancing_sbtab PARAMETER_BALANCING_SBTAB - Wrapper function for parameter balancing
parameter_balancing_thermodynamic PARAMETER_BALANCING_THERMODYNAMIC Thermodynamic parameter balancing