Description of parameter_balancing_model_matrices
Home > mnt > mnt-extensions > mnt_parameter_balancing > parameter_balancing > parameter_balancing_model_matrices.m
parameter_balancing_model_matrices
PURPOSE
SYNOPSIS
function model_matrices = parameter_balancing_model_matrices(network)
DESCRIPTION
CROSS-REFERENCE INFORMATION
This function calls:
network_numbers [nr,nm,nx,KM_indices,KA_indices,KI_indices,nKM,nKA,nKI] = network_numbers(network)
RT result = RT(temperature)
This function is called by:
parameter_balancing_construct_Q_matrix Q = parameter_balancing_construct_Q_matrix(quantities, basic_quantities, parameter_prior, network)