Description of pb_example_files
Home > mnt > mnt-extensions > mnt_parameter_balancing > parameter_balancing > pb_example_files.m
pb_example_files
PURPOSE
[model_file, data_file, prior_file, config_file] = pb_example_files(test_example);
SYNOPSIS
function [model_file, data_file, prior_file, config_file] = pb_example_files(test_example);
DESCRIPTION
 [model_file, data_file, prior_file, config_file] = pb_example_files(test_example);
CROSS-REFERENCE INFORMATION
This function calls:
get_pb_directory
This function is called by:
demo_pb_ecoli_noor_2016 ---------------------------------------------------------------------------------------------
demo_pb_ecoli_wortel_2018 -----------------------------------------------------------------------------------------
demo_pb_sbtab -------------------------------------------------------------------------