Description of ms_get_formula
Home > mnt-basic > mnt_kinetics > modular_rate_laws > ms_rate_law > ms_get_formula.m
ms_get_formula
PURPOSE
formula = ms_get_formula(r_name,mn,sub,pro,act,inh,m_sub,m_pro)
SYNOPSIS
function formula = ms_get_formula(r_name,mn,sub,pro,act,inh,m_sub,m_pro)
DESCRIPTION
 formula = ms_get_formula(r_name,mn,sub,pro,act,inh,m_sub,m_pro)
 mn: list of metabolite names
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
modular_kinetic_formulae [formula, global_assignment, local_assignment] = modular_kinetic_formulae(network)
network_get_kinetics_strings
network_sbml_export SBMLmodel = network_sbml_export(network, verbose, name, filename, notes, sbml_level, sbml_version)