Description of cycles
Home > mnt > mnt_fluxes > eba > eba_util > eba_beard > cycles.m
cycles
PURPOSE
C = cycles(N);
SYNOPSIS
function C = cycles(N);
DESCRIPTION
 C = cycles(N);
 compute cycle basis used in EBA
CROSS-REFERENCE INFORMATION
This function calls:
linear_combos Cnew = linear_combos(v1,v2);
test_new_vectors C = test_new_vectors(C,Cnew)
This function is called by:
eba_draw_cycles eba_draw_cycles(N,C)
eba_my_cycles wrapper around 'cycles', allowing to ignore some reactions
es_check_flux_constraints correct = es_check_flux_constraints(v,N,ind_ext,constraints,verbose,epsilon_stationary,C)
sample_feasible_v v = sample_feasible_v(N, ind_ext, constraints, options)
sample_fluxes_given_data [sample_v, best_v, C] = sample_fluxes_given_data(N, ind_ext, v_mean, v_std, n_sample_v, n_recombine_v, seed, ind_ignore, v_sign);
SOURCE CODE
function C = cycles(N);
% C = cycles(N);
%
% compute cycle basis used in EBA
C = null(N,'r');
n = size(C,2);
i = 1;
while i<n,
%  display(sprintf('check %d/%d',i,n))
  j = i+1;
  while j <= n
    Cnew = linear_combos(C(:,i), C(:,j));
    C    = test_new_vectors(C,Cnew);
    n    = size(C,2);
    j    = j+1;
  end
  i = i+1;
end