Description of demo_pb_ecoli_noor_2016
Home > mnt > mnt-extensions > mnt_parameter_balancing > demo > demo_pb_ecoli_noor_2016.m
demo_pb_ecoli_noor_2016
PURPOSE
---------------------------------------------------------------------------------------------
SYNOPSIS
This is a script file.
DESCRIPTION
 ---------------------------------------------------------------------------------------------
 Parameter balancing - Example E. coli central carbon metabolism model from Noor et al. (2016)
 Usage example for script 'parameter_balancing_sbtab'
 ---------------------------------------------------------------------------------------------
CROSS-REFERENCE INFORMATION
This function calls:
modular_rate_law_to_sbtab quantity_table = modular_rate_law_to_sbtab(network,filename,options)
parameter_balancing_check ECM_CHECK_PARAMETER_BALANCING - Checks for balanced parameters
pb_example_files [model_file, data_file, prior_file, config_file] = pb_example_files(test_example);
parameter_balancing_options PARAMETER_BALANCING_OPTIONS Options for parameter balancing - Data structure with default values
parameter_balancing_sbtab PARAMETER_BALANCING_SBTAB - Wrapper function for parameter balancing
This function is called by: