Description of cell_string2num
Home > mnt > mnt-basic > utils > cell_string2num.m
cell_string2num
PURPOSE
N = cell_string2num(C)
SYNOPSIS
function N = cell_string2num(C)
DESCRIPTION
 N = cell_string2num(C)
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
netgraph_print_positions [names, positions] = netgraph_print_positions(network,layout_file,offsets,policy,flag_KEGG_ids,flag_element_names,flag_fixed,flag_invisible)
sbtab_to_modular_rate_law [kinetics, sbtab_table, other_parameters] = sbtab_to_modular_rate_law(network,file_kinetic_data,options)
network_build_from_sum_formulae network = network_build_from_sum_formulas(filename_reactions,filename_compounds,columns)
data_integration_load_kinetic_data kinetic_data = data_integration_load_kinetic_data(data_quantities, parameter_prior, network, data_file, options)
parameter_balancing_check ECM_CHECK_PARAMETER_BALANCING - Checks for balanced parameters
parameter_balancing_prior parameter_prior = parameter_balancing_prior(omit_quantities,parameter_prior_filename)
parameter_balancing_task [task, prior] = parameter_balancing_task(network, kinetic_data, parameter_prior, model_quantities, basic_quantities,include_metabolic)