Description of default
Home > mnt > mnt-basic > utils > default.m
default
PURPOSE
commandstring = default(varname1,defaultvalue1,varname2,defaultvalue2,...)
SYNOPSIS
function commandstring = default(varargin)
DESCRIPTION
 commandstring = default(varname1,defaultvalue1,varname2,defaultvalue2,...)
 usage eval(default('a','1','name','''Gonzo'''));
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
eba_make_feasible v = eba_make_feasible(v,N,eba_condition,C,ind_ignore)
eba_v_and_mu [v,mu, value] = eba_v_and_mu(N,K,external,eba_constraints,eba_options,x0)
es_mu_simple_guess [A, mu, exitflag] = es_mu_simple_guess(N,v,es_constraints,zv,flag_reduce_network)
feasible_fluxes [v, C] = feasible_fluxes(N,ind_ext,data,es_constraints,eba_condition,C)
network_efmtool [C,mnet] = network_efmtool(network, method, ind_ignore, zv)
eba_feasible [feasible,C,ind_non_orthogonal] = eba_feasible(v,N,C,ind_ignore,eba_condition,cycle_method)
eba_feasible_lp [eba_feasible, dmu, dmu_abs_max] = eba_feasible_lp(v,Ntot,dmu_fix,dmu_abs_min,epsilon,dmu_abs_max)
es_check_flux_constraints isFeasible = es_check_flux_constraints(v,N,ind_ext,constraints,verbose,epsilon_stationary,C)
flux_check_stationarity
flux_least_squares_projection v = flux_least_squares_projection(network,v_pre)
project_fluxes v_projected = project_fluxes(N,ind_ext, v_mean, v_std, v_sign, pars);
sample_feasible_mu [mu, success_flag] = sample_feasible_mu(N,ind_ext,v,constraints,options,method,n_sample)
sample_fluxes_given_data [sample_v, best_v, C] = sample_fluxes_given_data(N, ind_ext, v_mean, v_std, n_sample_v, n_recombine_v, seed, ind_ignore, v_sign);
mdf [c,A] = mdf(N, v, keq, mdf_options)
mdf_default_options mdf_options = mdf_default_options(network,opt)
draw_metabolite_arcs draw_metabolite_arcs(network, colors, i1_list,i2_list, linewidth)
draw_reaction_arcs draw_reaction_arcs(network,colors,i1_list,i2_list,linewidth)
interaction_network_plot interaction_network_plot(network, reaction_values, reaction_pair_values, col, gp)
netgraph_assign_positions xpos = netgraph_assign_positions(network,picture,offsets,outfile)
netgraph_cofactor_graphs [network_CoHid,network_CoSplit] = netgraph_cofactor_graphs(network, metabolites_to_be_omitted, layout_file, max_met_degree,metabolites_to_be_kept)
netgraph_concentrations netgraph_concentrations(network,S,J,flag_text,options)
netgraph_double_movie [M,T] = netgraph_double_movie(network, t, s_t_1, s_t_2, data_type, n_frames, text_flag, options);
netgraph_edit_positions network = netgraph_edit_positions(network,layout_file,flag_KEGG_ids,flag_element_names,flag_fixed,flag_save_metabolites_as_fixed)
netgraph_flux_in_large_network [nn,M] = netgraph_flux_in_large_network(network,v,perc_show,table_positions,cofactors,not_cofactors,goptions_default)
netgraph_flux_movie M = netgraph_flux_movie(network,S,J,text_flag,goptions);
netgraph_fluxes netgraph_fluxes(network,J,gp)
netgraph_make_graph network = netgraph_make_graph(network,metvalues,actvalues,set_positions,x_init,table_positionss);
netgraph_mark_reactions [choice,p] = netgraph_mark_reactions(network,choice,draw_only)
netgraph_metabolite_interactions netgraph_metabolite_interactions(network, influence_values, interaction_values, col, gp)
netgraph_move network = netgraph_move(network,flag_draw_details,options,picture,filename_in,filename_out)
netgraph_movie [M,T] = netgraph_movie(network, t, s_t, data_type, n_frames, text_flag, options);
netgraph_print_positions [names, positions] = netgraph_print_positions(network,layout_file,offsets,policy,flag_KEGG_ids,flag_element_names,flag_fixed,flag_invisible)
netgraph_read_positions network = netgraph_read_positions(network,layout_file,offsets,fill_nans,flag_KEGG_ids, reaction_KEGG_IDs, flag_fixed)
netgraph_simple_graph [n2,keep_met,keep_react] = netgraph_simple_graph(n1,met_hide,met_fixed,met_fixed_positions,react_hide)
convenience2vector [vector,names,types,relevant_reactions] = convenience2vector(kinetics,network,no_names)
convenience_parameter_vector_indices types = convenience_parameter_vector_indices(network,dynamic_flag,n_exp,dependent_flag,nw)
convenience_velocities v = convenience_velocities(s,network,kinetics,indices,split,scale_G,offset_ratio)
convert_kG_to_G [G,G_std] = convert_kG_to_G(kG,rt,kG_std)
convert_kG_to_kEQ kEQ = convert_kG_to_kEQ(kG,N,RT)
parameters2vector [vector,names,relevant,relevant_reactions,types] = parameters2vector(kinetics,S_ext,S_ext_names,network,split,no_names)
set_cs_kinetics kinetics = set_cs_kinetics(network,parameters)
compute_modular_elasticities E = compute_modular_elasticities(kinetic_law, N, W, ind_ext, alpha_A, alpha_I, alpha_M, v, A, u, c, h, v_plus_fallback, v_minus_fallback,flag_second_order)
compute_modular_kX_elasticities [E_kX_sc,kX_names,kX] = compute_modular_kX_elasticities(kinetic_law,network, c);
compute_modular_response_second [Rtarget_sc_u, Rtarget_sc_uu] = compute_modular_control_second(zc_scaled, zv_scaled, kinetic_law, N, W, ind_ext, alpha_A, alpha_I, alpha_M, v, A, u, c, h, v_plus_fallback, v_minus_fallback, CS_un, CJ_un)
elasticities_to_parameters kinetics = elasticities_to_parameters(network,E_sc,v,c,u,A,h)
modular_rate_law_to_sbtab quantity_table = modular_rate_law_to_sbtab(network,filename,options)
mrl_display_reaction_parameters
mrl_kinetics_to_sbtab s = mrl_kinetics_to_sbtab(network, kinetics, parameter_prior, save_quantities, file_basename)
ms_import_kinetic [kin_data,parameter_prior] = ms_import_kinetic(network,kinetic_balanced_file)
alpha_to_k KX = alpha_to_k(alpha_X,c,hill)
k_to_alpha [alpha_X,beta_X] = k_to_alpha(KX,c,hill);
k_to_log_alpha log_alpha_X,log_beta_X: sparse matrices
modular_KV_Keq_to_kcat [kcatplus, kcatminus] = modular_kcat_to_KV_Keq(N,kinetics,KV,Keq,KM)
modular_kcat_linear_to_KV_Keq [kinetics,KV,Keq] = modular_kcat_linear_to_KV_Keq(N,kinetics,kcat_linear_plus,kcat_linear_minus,Keq)
modular_kcat_to_KV_Keq [kinetics,KV,Keq] = modular_kcat_to_KV_Keq(N,kinetics,kcatplus,kcatminus,Keq)
ms_compute_Kcat [kcatplus,kcatminus] = ms_compute_Kcat(N,KM,KV,Keq);
ms_compute_log_Kcat [log_kcatplus,log_kcatminus] = ms_compute_log_Kcat(N,KM,KV,Keq,h);
sbtab_to_modular_rate_law [kinetics, sbtab_table, other_parameters] = sbtab_to_modular_rate_law(network,file_kinetic_data,options)
sbtab_to_modular_rate_law_via_kinetic_data [kinetics, kinetic_data] = sbtab_to_modular_rate_law(network,file_kinetic_data,options)
set_ms_kinetics kinetics = set_ms_kinetics(network,parameters)
basic_control_analysis R = basic_control_analysis(network,s,options)
control_coefficients [CJ, CS, L_int, NR_int, M, M_adj, indp_among_internal] = control_coefficients(N, Ec, external, used, NR_int, L_int, indp_among_internal,dilution_rate)
elasticities [Ec,Ep,parameters,Ecc,Ecp,Epp,p] = elasticities(network,s,options);
response_coefficients_numerical [RS,RJ,RS2,RJ2] = response_coefficients_numerical(network,c,ind_rel_par)
response_coefficients_target_numerical [RZp,RZpp] = response_coefficients_target_numerical(network,c,ind_rel_par,zc,zv)
spectral_response_coefficients [RS, RJ, RS_2_2omega, RJ_2_2omega, RS_2_2omega0, RJ_2_2omega0, CS,CS_2_omega,CJ,CJ_2_omega] = ...
network_add_reaction network = network_add_reaction(network,reactants,stoich_coeffs,name,reversible);
network_add_transport network = network_add_transport(network, metabolites,flag_only_reactions);
network_build_from_sum_formulae network = network_build_from_sum_formulas(filename_reactions,filename_compounds,columns)
network_construct network = network_construct(N,reversible,ind_external,metabolites,actions,no_graphics,regulation_matrix,flag_kinetics)
network_print_formulae all_result = network_print_formulae(network,actions,metabolites,all_reversible)
network_reduce_to_active_subnetwork if v is a matrix, choose all reactions for which the flux in any of the states
network_remove_action [network1,keep,keep_actions] = network_remove_action(network,ind,flag_remove_metabolites)
network_subnetwork [subnetwork, ind_m, ind_r] = network_subnetwork(network,ind_m,ind_r,omit_isolated_metabolites)
network_subnetwork_balanced [network_red,v_red,dmu_red,c_red] = network_subnetwork_balanced(network,v,epsilon,vmin,dmu,c)
cobra_to_network [network, ind_keepm, ind_keepr] = cobra_to_network(model,options)
network2sbml string = network2sbml(network,verbose,name,filename,write_equilibrium_constants)
network_adjust_names_for_sbml_export [metabolites,actions] = network_adjust_names_for_sbml_export(metabolites,actions)
network_sbml_export SBMLmodel = network_sbml_export(network, verbose, name, filename, notes, sbml_level, sbml_version)
network_sbml_import [network,s] = network_sbml_import(s,dirname,verbose)
network_to_cobra model = network_translate_to_cobra(network,description,vz)
network_to_sbtab sbtab_document = network_to_sbtab(network, options)
sbtab_to_network function network = sbtab_to_network(filename,options)
make_structure_matrices [Mplus, Mminus, Wplus, Wminus, nm, nr, N_int,ind_M,ind_Wp,ind_Wm] = make_structure_matrices(N,W,ind_ext,h)
RT result = RT(temperature)
network_integrate_kin [t,x,v,t_pre,x_pre,p_p_pre] = network_integrate_kin(x0,pp,T1,T2,N,velocity_function,delta_par,external,volumes,verbose_flag)
network_steady_state [S, J, Sdot, error] = network_steady_state(network,s,integrate_time,L_int,NR_int,indep_met_int,dilution_rate)
thermo_pb [c,A] = thermo_pb(N, v, thermo_pb_options, verbose)
annotate_list list2 = annotate_list(list1,filename,filetype)
arc -------------------------
circle circle(x,y,r,col,filled,linewidth)
convex_sampling [x, x_lower. x_upper, success_flag, x_lower_list, x_upper_list] = convex_sampling(A_ineq,b_ineq,A_eq,b_eq,n_sample,xl,xu);
convex_sampling_rejection_no_eq [x, x_lower. x_upper, success_flag, x_lower_list, x_upper_list] = convex_sampling_rejection_no_eq(A_ineq,b_ineq,A_eq,b_eq,n_sample,xl,xu,verbose,options);
dot_matrix dot_matrix(Mmean,Mstd,max_val,max_diameter,col,flag_legend,textrow,textcol)
graph_circle_plot
guess_flux_std flux_std = guess_flux_std(flux_data,alpha,beta);
lognormal_log2normal [mu,sigma] = lognormal_log2normal(mu_log,sigma_log,convention)
lognormal_normal2log function [mu_log,sigma_log] = lognormal_normal2log(mu,sigma,convention)
movie_save movie_save(filename,M,resolution)
my_colorbar my_colorbar(vmin,vmax,n_step,location,showsign,cm)
my_colors function col = my_colors(n)
my_feather my_feather(z,l,centres,d,color,options)
my_spectrum
my_xticklabel
mytable result = mytable(names,rownumbers,filename)
pm
rb_colors c = rb_colors(ncol)
rby_colors
ryb_colors
sunrise_colors function col = sunrise_colors(n)
data_integration_bounds_pseudovalues kinetic_data = data_integration_bounds_pseudovalues(kinetic_data,parameter_prior,insert_pseudo_values,network);
data_integration_display_kinetic_data T = data_integration_display_kinetic_data(kinetic_data,network,flag_display)
data_integration_load_kinetic_data kinetic_data = kinetic_data = data_integration_load_kinetic_data(data_quantities, parameter_prior, network, data_file, use_sbml_ids, use_kegg_ids, flag_invent_std, verbose, filter_column, filter_entry, reaction_column_name, compound_column_name)
data_integration_save_kinetic_data M = data_integration_save_kinetic_data(kinetic_data,network,filename,options_style)
load_flux_data [v, v_std] = load_flux_data(network, flux_data_filename)
model_reduction model_reduction - Replace parts of biochemical network models by simple linear systems
selective_reduction r = selective_reduction(network, subsystem_metabolites, S, J, Ec_un, Ep_un);
demo_pb_sbtab -------------------------------------------------------------------------
parameter_balancing PARAMETER_BALANCING Read model from SBML file; read data and general options from SBtab files; write results to output files
parameter_balancing_Keq [Keq, mu0, c, my_kinetic_data] = parameter_balancing_Keq(network, filename,options)
parameter_balancing_calculation [result, exitflag] = parameter_balancing(task, parameter_prior, options)
parameter_balancing_check ECM_CHECK_PARAMETER_BALANCING - Checks for balanced parameters
parameter_balancing_constrained_sampling [q_sample, xmodel_sample, xdata_sample, kinetics_sample, v_sample, q_min, q_max] = parameter_balancing_constrained_sampling(task,res,options,parameter_prior)
parameter_balancing_output [r_mode, r_mean, r_std, r_geom_mean, r_geom_std, r_orig, r_samples, r_flux_adjusted, r_flux_adjusted_std] = parameter_balancing_output(res,kinetic_data_orig,options)
parameter_balancing_prior parameter_prior = parameter_balancing_prior(omit_quantities,parameter_prior_filename)
parameter_balancing_quantities [model_quantities, basic_quantities, data_quantities, pseudo_quantities] = parameter_balancing_relevant_quantities(parameter_prior,network,options)
parameter_balancing_sample_models
parameter_balancing_task [task, prior] = parameter_balancing_task(network, kinetic_data, parameter_prior, model_quantities, basic_quantities,include_metabolic)
parameter_balancing_kinetic PARAMETER_BALANCING_KINETIC Determine a consistent kinetic parameter set
parameter_balancing_thermodynamic PARAMETER_BALANCING_THERMODYNAMIC Thermodynamic parameter balancing
spectral_response SPECTRAL_RESPONSE - Compute response of kinetic model to parameter oscillation
my_feather my_feather(z,l,centres,d,color,options)
osc_resp_plot_timecourses [RS_omega,RV_omega] = osc_resp_plot_timecourses(network,t_appr,x_ss,v_ss,t,x,v,M0,delta_par_struct,epsilon_1,pi_1,epsilon_2,rho_2,pi_2,color,orderx,orderv)
oscillatory_response this is an updated version of osc_resp_plot_timecourse
oscillatory_response_plot this is an updated version of osc_resp_plot_timecourse
oscillatory_response_rectangular this is an updated version of osc_resp_plot_timecourse
spec_resp_par_sensitivity this is an updated version of osc_resp_plot_timecourse