Description of join_struct
Home > mnt > mnt-basic > utils > join_struct.m
join_struct
PURPOSE
a = join_struct(a,b)
SYNOPSIS
function a = join_struct(a,b)
DESCRIPTION
 a = join_struct(a,b)
 start with structure a and insert all fields from structure b
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
project_fluxes v_projected = project_fluxes(N,ind_ext, v_mean, v_std, v_sign, pars);
mdf_default_options mdf_options = mdf_default_options(network,opt)
interaction_network_plot interaction_network_plot(network, reaction_values, reaction_pair_values, col, gp)
netgraph_concentrations netgraph_concentrations(network,S,J,flag_text,options)
netgraph_double_movie [M,T] = netgraph_double_movie(network, t, s_t_1, s_t_2, data_type, n_frames, text_flag, options);
netgraph_draw netgraph_draw(network,varargin)
netgraph_edit_positions network = netgraph_edit_positions(network,layout_file,flag_KEGG_ids,flag_element_names,flag_fixed,flag_save_metabolites_as_fixed)
netgraph_flux_in_large_network [nn,M] = netgraph_flux_in_large_network(network,v,perc_show,table_positions,cofactors,not_cofactors,goptions_default)
netgraph_flux_movie M = netgraph_flux_movie(network,S,J,text_flag,goptions);
netgraph_fluxes netgraph_fluxes(network,J,gp)
netgraph_metabolite_interactions netgraph_metabolite_interactions(network, influence_values, interaction_values, col, gp)
netgraph_move network = netgraph_move(network,flag_draw_details,options,picture,filename_in,filename_out)
netgraph_movie [M,T] = netgraph_movie(network, t, s_t, data_type, n_frames, text_flag, options);
modular_rate_law_to_sbtab quantity_table = modular_rate_law_to_sbtab(network,filename,options)
sbtab_to_modular_rate_law [kinetics, sbtab_table, other_parameters] = sbtab_to_modular_rate_law(network,file_kinetic_data,options)
sbtab_to_modular_rate_law_via_kinetic_data [kinetics, kinetic_data] = sbtab_to_modular_rate_law(network,file_kinetic_data,options)
basic_control_analysis R = basic_control_analysis(network,s,options)
elasticities [Ec,Ep,parameters,Ecc,Ecp,Epp,p] = elasticities(network,s,options);
network_build_from_sum_formulae network = network_build_from_sum_formulas(filename_reactions,filename_compounds,columns)
cobra_to_network [network, ind_keepm, ind_keepr] = cobra_to_network(model,options)
network_to_sbtab sbtab_document = network_to_sbtab(network, options)
sbtab_to_network function network = sbtab_to_network(filename,options)
my_feather my_feather(z,l,centres,d,color,options)
model_reduction model_reduction - Replace parts of biochemical network models by simple linear systems
parameter_balancing PARAMETER_BALANCING Read model from SBML file; read data and general options from SBtab files; write results to output files
parameter_balancing_Keq [Keq, mu0, c, my_kinetic_data] = parameter_balancing_Keq(network, filename,options)
parameter_balancing_calculation [result, exitflag] = parameter_balancing(task, parameter_prior, options)
parameter_balancing_constrained_sampling [q_sample, xmodel_sample, xdata_sample, kinetics_sample, v_sample, q_min, q_max] = parameter_balancing_constrained_sampling(task,res,options,parameter_prior)
parameter_balancing_quantities [model_quantities, basic_quantities, data_quantities, pseudo_quantities] = parameter_balancing_relevant_quantities(parameter_prior,network,options)
parameter_balancing_sample_models
parameter_balancing_update_options
parameter_balancing_kinetic PARAMETER_BALANCING_KINETIC Determine a consistent kinetic parameter set
parameter_balancing_sbtab PARAMETER_BALANCING_SBTAB - Wrapper function for parameter balancing
parameter_balancing_thermodynamic PARAMETER_BALANCING_THERMODYNAMIC Thermodynamic parameter balancing
my_feather my_feather(z,l,centres,d,color,options)