Description of my_colors
Home > mnt > mnt-basic > utils > my_colors.m
my_colors
PURPOSE
function col = my_colors(n)
SYNOPSIS
function col = my_colors(n)
DESCRIPTION
 function col = my_colors(n)
CROSS-REFERENCE INFORMATION
This function calls:
default commandstring = default(varname1,defaultvalue1,varname2,defaultvalue2,...)
This function is called by:
ryb_colors
model_reduction_draw_figures info = model_reduction_draw_figures(network,r,tF,s_tF,tR,s_tR,x_tR,tE,s_tE,weights,Tr,metabolites_subsystem,subsystem2_metabolites,gp,network_CoHid)