Description of mytable
Home > mnt > mnt-basic > utils > mytable.m
mytable
PURPOSE
result = mytable(names,rownumbers,filename)
SYNOPSIS
function res = mytable(names,rownumbers,filename)
DESCRIPTION
result = mytable(names,rownumbers,filename)
display cell array of strings to file
flag rownumbers: 0 (none), 1 (yes) ,'tex' (tex style)
(if filename is given -> output to file)
CROSS-REFERENCE INFORMATION
This function calls:
default commandstring = default(varname1,defaultvalue1,varname2,defaultvalue2,...)
This function is called by:
netgraph_assign_positions xpos = netgraph_assign_positions(network,picture,offsets,outfile)
mrl_kinetics_to_sbtab s = mrl_kinetics_to_sbtab(network, kinetics, parameter_prior, save_quantities, file_basename)
network_build_from_sum_formulae network = network_build_from_sum_formulas(filename_reactions,filename_compounds,columns)
network_list_allosteric network_list_allosteric(network)
network_print_conservation_relations network_print_conservation_relations(network,G)
print_matrix b = print_matrix(matrix,rownames,colnames)
data_integration_display_kinetic_data T = data_integration_display_kinetic_data(kinetic_data,network,flag_display)
data_integration_load_kinetic_data kinetic_data = data_integration_load_kinetic_data(data_quantities, parameter_prior, network, data_file, options)
data_integration_save_kinetic_data M = data_integration_save_kinetic_data(kinetic_data,network,filename,options_style)
model_reduction model_reduction - Replace parts of biochemical network models by simple linear systems
demo_pb_ecoli_wortel_2018 -----------------------------------------------------------------------------------------
parameter_balancing_check ECM_CHECK_PARAMETER_BALANCING - Checks for balanced parameters
parameter_balancing_task [task, prior] = parameter_balancing_task(network, kinetic_data, parameter_prior, model_quantities, basic_quantities,include_metabolic)