Description of subplot_n
Home > mnt > mnt-basic > utils > subplot_n.m
subplot_n
PURPOSE
SYNOPSIS
function [ni,nk]=subplot_n(N)
DESCRIPTION
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
network_integrate_par_pert [t, s, v, p, s_int, met_int] = network_integrate_par_pert(network, s, T, gf, par_osc, dt)
parameter_balancing_check ECM_CHECK_PARAMETER_BALANCING - Checks for balanced parameters
osc_resp_plot_timecourses [RS_omega,RV_omega] = osc_resp_plot_timecourses(network,t_appr,x_ss,v_ss,t,x,v,M0,delta_par_struct,epsilon_1,pi_1,epsilon_2,rho_2,pi_2,color,orderx,orderv)
oscillatory_response_plot this is an updated version of osc_resp_plot_timecourse
spec_resp_par_sensitivity this is an updated version of osc_resp_plot_timecourse