Description of network_add_metabolites
Home > mnt > mnt_network > network_build_edit > network_add_metabolites.m
network_add_metabolites
PURPOSE
network = network_add_metabolites(network,new_metabolites,new_external);
SYNOPSIS
function network = network_add_metabolites(network,new_metabolites,new_external);
DESCRIPTION
 network = network_add_metabolites(network,new_metabolites,new_external);
CROSS-REFERENCE INFORMATION
This function calls:
network_numbers [nr,nm,nx,KM_indices,KA_indices,KI_indices,nKM,nKA,nKI] = network_numbers(network)
column transform a vector (row or column) into a column vector
This function is called by:
network_add_reaction network = network_add_reaction(network,reactants,stoich_coeffs,name,reversible);
SOURCE CODE
function network = network_add_metabolites(network,new_metabolites,new_external);
% network = network_add_metabolites(network,new_metabolites,new_external);
new_metabolites = column(setdiff(new_metabolites,network.metabolites));
[nr,nm] = network_numbers(network);
nn = length(new_metabolites);
if ~exist('new_external','var'),
  new_external =  ones(nn,1);
end
network.metabolites       = [network.metabolites; new_metabolites];
network.external          = [network.external; new_external];
network.N                 = [network.N; zeros(nn,nr)];
network.regulation_matrix = [network.regulation_matrix, zeros(nr,nn)];
if isfield(network,'s_init'),
  network.s_init            = [network.s_init; nan*zeros(nn,1)];
end
if isfield(network,'metabolite_names'),
  network.metabolite_names = [network.metabolite_names; new_metabolites];
end
if isfield(network,'metabolite_compartments'),
  network.metabolite_compartments = [network.metabolite_compartments; repmat({''},nn,1)];
end
if isfield(network,'metabolite_KEGGID'),
  network.metabolite_KEGGID = [network.metabolite_KEGGID; repmat({'unknown_KEGG_ID'},nn,1)];
end