Description of network_add_reaction
Home > mnt > mnt_network > network_build_edit > network_add_reaction.m
network_add_reaction
PURPOSE
network = network_add_reaction(network,reactants,stoich_coeffs,name,reversible);
SYNOPSIS
function network = network_add_reaction(network,reactants,stoich_coeffs,name,reversible,external);
DESCRIPTION
 network = network_add_reaction(network,reactants,stoich_coeffs,name,reversible);
CROSS-REFERENCE INFORMATION
This function calls:
network_add_metabolites network = network_add_metabolites(network,new_metabolites,new_external);
network_find_metabolites indices = network_find_metabolites(network,metabolite)
network_numbers [nr,nm,nx,KM_indices,KA_indices,KI_indices,nKM,nKA,nKI] = network_numbers(network)
network_print_formulae all_result = network_print_formulae(network,actions,metabolites,all_reversible)
column transform a vector (row or column) into a column vector
default commandstring = default(varname1,defaultvalue1,varname2,defaultvalue2,...)
label_names function [label,indices] = label_names(names,allnames, method)
This function is called by:
SOURCE CODE
function network = network_add_reaction(network,reactants,stoich_coeffs,name,reversible,external);
% network = network_add_reaction(network,reactants,stoich_coeffs,name,reversible);
eval(default('reversible','1'));
stoich_coeffs = column(stoich_coeffs);
new_metabolites = setdiff(reactants,network.metabolites);
new_external = external(label_names(new_metabolites,reactants));
if length(new_metabolites),
  network = network_add_metabolites(network,new_metabolites,new_external);
end
[nr,nm] = network_numbers(network);
ind    = network_find_metabolites(network,reactants);
network.actions                   = [network.actions; name];
network.N(ind,nr+1)               = stoich_coeffs;
network.regulation_matrix(nr+1,:) = 0;
network.reversible                = [network.reversible; reversible];
if isfield(network, 'reaction_names'),
  network.reaction_names = [network.reaction_names; {name}];
end
if isfield(network, 'formulae'),
  network.formulae = network_print_formulae(network);
end