Description of network_listchoose_metabolites
Home > mnt > mnt_network > network_build_edit > network_listchoose_metabolites.m
network_listchoose_metabolites
PURPOSE
[n_sub,metindices] = network_listchoose_metabolites(network,metnames,indices)
SYNOPSIS
function [n_sub,met,actindices,metindices] = network_listchoose_metabolites(network,metnames,indices)
DESCRIPTION
 [n_sub,metindices] = network_listchoose_metabolites(network,metnames,indices)
CROSS-REFERENCE INFORMATION
This function calls:
netgraph_make_graph network = netgraph_make_graph(network,metvalues,actvalues,set_positions,x_init,table_positionss);
network_choose [subnetwork,indm,indr] = network_choose(network,indm,indr)
listbox [indices,h] = listbox(list,indices);
This function is called by:
SOURCE CODE
% [n_sub,metindices] = network_listchoose_metabolites(network,metnames,indices)
function [n_sub,met,actindices,metindices] = network_listchoose_metabolites(network,metnames,indices)
if ~exist('metnames','var'); metnames = network.metabolites; end
if ~exist('indices','var'); indices = []; end
[met,h] = listbox(metnames,indices);
 actindices = find(sum(network.N(met,:)~=0,1));
metindices = find(sum(network.N(:,actindices)~=0,2));
n_sub = network_choose(network,metindices,actindices);
n_sub = netgraph_make_graph(n_sub);