Description of network_listchoose_actions
Home > mnt > mnt_network > network_build_edit > network_listchoose_actions.m
network_listchoose_actions
PURPOSE
[n_sub,actindices] = network_listchoose_actions(network,actnames,indices)
SYNOPSIS
function [n_sub,actindices,metindices] = network_listchoose_actions(network,actnames,indices)
DESCRIPTION
 [n_sub,actindices] = network_listchoose_actions(network,actnames,indices)
CROSS-REFERENCE INFORMATION
This function calls:
netgraph_make_graph network = netgraph_make_graph(network,metvalues,actvalues,set_positions,x_init,table_positionss);
network_choose [subnetwork,indm,indr] = network_choose(network,indm,indr)
listbox [indices,h] = listbox(list,indices);
This function is called by:
SOURCE CODE
% [n_sub,actindices] = network_listchoose_actions(network,actnames,indices)
function [n_sub,actindices,metindices] = network_listchoose_actions(network,actnames,indices)
if ~exist('actnames','var'); actnames = network.actions; end
if ~exist('indices','var'); indices = []; end
[actindices,h] = listbox(actnames,indices);
metindices = find(sum(network.N(:,actindices)~=0,2));
%actindices = find(sum(network.N(metindices,:)~=0,1));
n_sub = network_choose(network,metindices,actindices);
n_sub = netgraph_make_graph(n_sub);