Description of compute_modular_kX_elasticities
Home > mnt > mnt-basic > mnt_kinetics > modular_rate_laws > modular_rate_law_functions > compute_modular_kX_elasticities.m
compute_modular_kX_elasticities
PURPOSE
[E_kX_sc,kX_names,kX] = compute_modular_kX_elasticities(kinetic_law,network, c);
SYNOPSIS
function [E_kX_sc,kX_names,kX] = compute_modular_kX_elasticities(kinetic_law,network, c);
DESCRIPTION
 [E_kX_sc,kX_names,kX] = compute_modular_kX_elasticities(kinetic_law,network, c);
CROSS-REFERENCE INFORMATION
This function calls:
compute_cs_kX_elasticities [E_kX_sc,kX_names,kX] = compute_cs_kX_elasticities(network, c);
compute_ms_kX_elasticities [E_kX_sc,kX_names,kX] = compute_ms_kX_elasticities(network, c);
default commandstring = default(varname1,defaultvalue1,varname2,defaultvalue2,...)
This function is called by: