Description of netgraph_make_CoHid
Home > mnt > mnt_graphics > netgraph_make_CoHid.m
netgraph_make_CoHid
PURPOSE
SYNOPSIS
This is a script file.
DESCRIPTION
CROSS-REFERENCE INFORMATION
This function calls:
netgraph_cofactor_graphs
netgraph_make_graph network = netgraph_make_graph(network,metvalues,actvalues,set_positions,x_init,table_positionss);
netgraph_simple_graph [n2,keep_met,keep_react] = netgraph_simple_graph(n1,met_hide,met_fixed,positions)
This function is called by:
SOURCE CODE
max_met_degree = 6; % sqrt(nr)
met_degree = sum(abs(sign(network.N)),2);
cofactors       = network.metabolites(met_degree>max_met_degree);
network         = netgraph_make_graph(network);
network_CoHid   = netgraph_simple_graph(network,cofactors);
% find_EX         = find(cellfun('length',strfind(network.metabolites,'[e]')));
% network_CoHid.graphics_par.x = 0 * network_CoHid.graphics_par.x;
% network_CoHid.graphics_par.x(:,find_EX) = [cos(2*pi*1/length(find_EX)*[0:length(find_EX)-1]); sin(2*pi*1/length(find_EX)*[0:length(find_EX)-1]);];
% network_CoHid.graphics_par.fixed = 0 * network_CoHid.graphics_par.fixed;
% network_CoHid.graphics_par.fixed(find_EX) = 1;
table_positions = '/tmp/network_positions';
! rm /tmp/network_positions
! touch /tmp/network_positions
save('/tmp/network','network','network_CoHid');
ncsp_change_positions(struct('network_file','/tmp/network','table_positions',table_positions),network.graphics_par,cofactors);
[network_CoHid,network_CoSplit] = netgraph_cofactor_graphs(network, cofactors, table_positions);