Description of netgraph_define_module
Home > mnt > mnt_graphics > netgraph_define_module.m
netgraph_define_module
PURPOSE
m = netgraph_define_module(network)
SYNOPSIS
function [m,n] = netgraph_define_module(network)
DESCRIPTION
 m = netgraph_define_module(network)
 choose the members of a network module
CROSS-REFERENCE INFORMATION
This function calls:
netgraph_mark_metabolites [choice,p] = netgraph_mark_metabolites(network,choice,draw_only)
set_kinetics kinetics = set_kinetics(network,type,parameters)
network_choose [subnetwork,indm,indr] = network_choose(network,indm,indr)
This function is called by:
SOURCE CODE
function [m,n] = netgraph_define_module(network)
% m = netgraph_define_module(network)
% choose the members of a network module
[m,p] = netgraph_mark_metabolites(network);
m = find(m);
if nargout>1,
n = network_choose(network,m);
n.kinetics = set_kinetics(n,network.kinetics.type)
end