Description of netgraph_edit_positions
Home > mnt > mnt_graphics > netgraph_edit_positions.m
netgraph_edit_positions
PURPOSE
network = netgraph_edit_positions(network,table_positions,flag_KEGG_ids)
SYNOPSIS
function network = netgraph_edit_positions(network,table_positions,flag_KEGG_ids,gp,reaction_KEGG_IDs)
DESCRIPTION
 network = netgraph_edit_positions(network,table_positions,flag_KEGG_ids)
 flag_KEGG_ids  which name field in 'network' to use: metabolite_KEGGID or metabolites
CROSS-REFERENCE INFORMATION
This function calls:
netgraph_move network = netgraph_move(network,flag_draw_details,options,picture,filename_in,filename_out)
netgraph_print_positions output = netgraph_print_positions(network,filename,offsets,policy,flag_KEGG_ids)
netgraph_read_positions network = netgraph_read_positions(network,table_positions,offsets,fill_nans,flag_KEGG_ids)
default commandstring = default(varname1,defaultvalue1,varname2,defaultvalue2,...)
join_struct c = join_struct(a,b)
This function is called by:
SOURCE CODE
function network = netgraph_edit_positions(network,table_positions,flag_KEGG_ids,gp,reaction_KEGG_IDs)
% network = netgraph_edit_positions(network,table_positions,flag_KEGG_ids)
% flag_KEGG_ids  which name field in 'network' to use: metabolite_KEGGID or metabolites
eval(default('flag_KEGG_ids','0','gp','struct','reaction_KEGG_IDs','[]'));
if length(reaction_KEGG_IDs),
  network.reaction_KEGGID = reaction_KEGG_IDs;
end
gp_default.actprintnames = 0;
gp = join_struct(gp_default,gp);
network = netgraph_read_positions(network,table_positions,[0,0],1,flag_KEGG_ids);
network = netgraph_move(network,'all',gp);
netgraph_print_positions(network,table_positions,[0,0],'replace elements',flag_KEGG_ids);
display(sprintf('New positions saved to file %s',table_positions));