Description of netgraph_concentrations
Home > mnt > mnt_graphics > netgraph_concentrations.m
netgraph_concentrations
PURPOSE
netgraph_concentrations(network,S,J,flag_text,options)
SYNOPSIS
function netgraph_concentrations(network,S,J,flag_text,options)
DESCRIPTION
 netgraph_concentrations(network,S,J,flag_text,options)
 display concentrations and (optionally) fluxes
CROSS-REFERENCE INFORMATION
This function calls:
netgraph_draw netgraph_draw(network,varargin)
default commandstring = default(varname1,defaultvalue1,varname2,defaultvalue2,...)
join_struct c = join_struct(a,b)
This function is called by:
eba_draw_cycles eba_draw_cycles(N,C)
es_mu_simple_guess [A, mu, exitflag] = es_mu_simple_guess(N,v,es_constraints,zv,flag_reduce_network)
flux2entropy_production [mu,A,R] = flux2entropy_production(network,v,mu_ext)
optimise_entropy_flux [v, mu, A] = optimise_entropy_flux(network, kappa, mu_ext)
interaction_network_plot interaction_network_plot(network, reaction_values, reaction_pair_values, col, gp)
netgraph_flux_movie M = netgraph_flux_movie(network,S,J,text_flag,goptions);
netgraph_metabolite_interactions netgraph_metabolite_interactions(network, influence_values, interaction_values, col, gp)
netgraph_movie [M,T] = netgraph_movie(network, t ,s_t, data_type, n_frames, text_flag, options);
netgraph_wheelplot netgraph_wheelplot(network,network_CoHid,data,pars,wheelpars)
SOURCE CODE
% netgraph_concentrations(network,S,J,flag_text,options)
%
% display concentrations and (optionally) fluxes
function netgraph_concentrations(network,S,J,flag_text,options)
eval(default('S','[]','J','[]','flag_text','0','options','struct'));
opt_def = struct('actstyle','none','arrowvalues',[],'actprintnames',0,'flag_edges',1,'arrowvaluesmax',max(abs(J)));%,'colormap',rb_colors);
if isfield(options,'arrowvalues'),
  opt_def.arrowvaluesmax = max(abs(options.arrowvalues));
  opt_def.arrowstyle = 'fluxes';
  opt_def.actstyle = 'fluxes';
else
  opt_def.arrowstyle  = 'none';
end
if length(J),
  opt_def.actstyle = 'fixed';
end
eval(default('options','struct'));
options = join_struct(opt_def,options);
if strcmp(options.actstyle, 'none'),
  if isempty(options.arrowvalues),
    options.arrowvalues = J;
    options.arrowstyle = 'fluxes';
  end
end
opt = struct('metstyle','fixed','metvalues',S,'actvalues',J,'arrowcolor',[0.7 0.7 0.7],'linecolor',[0 0 0]);
if isempty(J),
%  opt = join_struct(opt,struct('arrowstyle','none'));
else
  if length(J)==1, J=J*ones(size(network.actions)); end
  opt = join_struct(opt,struct('arrowvalues',J,'arrowstyle','fluxes'));
end
if ~flag_text,
  opt = join_struct(opt, struct('metprintnames',0,'actprintnames',0));
end
opt = join_struct(opt,options);
netgraph_draw(network, opt);
set(gcf,'Color',[1 1 1]);