Description of label_names
Home > mnt > utils > label_names.m
label_names
PURPOSE
function [label,indices] = label_names(names,allnames, method)
SYNOPSIS
function [label,indices] = label_names(names,allnames,method)
DESCRIPTION
 function [label,indices] = label_names(names,allnames, method)
 method 'multiple'
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
data_integration_load_kinetic_data kinetic_data = data_integration_load_kinetic_data(data_quantities, quantity_info, network, file_kinetic_data, use_sbml_ids, use_kegg_ids, flag_invent_std, verbose)
data_integration_load_quantity_info quantity_info = data_integration_load_quantity_info(omit_quantities,quantity_info_filename)
model_reduction model_reduction - Replace parts of biochemical network models by simple linear systems
model_reduction_simulations [tF,s_tF,tR,s_tR,x_tR,tE,s_tE,weights,Tr,environment_metabolites] = model_reduction_simulations(network,r,metabolites_subsystem,S,J,s_initial,t_max,ndim,verbose)
selective_reduction r = selective_reduction(network, subsystem_metabolites, S, J, Ec_un, Ep_un);
parameter_balancing_construct_Q_matrix Q = parameter_balancing_construct_Q_matrix(quantities, basic_quantities, quantity_info, network)
parameter_balancing_kinetic [r,r_orig,kinetic_data] = parameter_balancing_kinetic(network, kinetic_data, filename, Keq_given);
parameter_balancing_task Prepare vectors and matrices for parameter balancing
parameter_balancing_thermodynamic [c, v, mu0, Keq, A, my_kinetic_data] = parameter_balancing_theromdynamic(network, v, filename,options)
spec_resp_par_sensitivity this is an updated version of osc_resp_plot_timecourse
fba_adjust_fluxes_thresholds fba_constraints = fba_adjust_fluxes_thresholds(network,fba_constraints)
netgraph_draw netgraph_draw(network,varargin)
netgraph_move network = netgraph_move(network,flag_draw_details,options,picture,filename_in,filename_out)
netgraph_print_positions output = netgraph_print_positions(network,filename,offsets,policy,flag_KEGG_ids)
netgraph_read_positions network = netgraph_read_positions(network,table_positions,offsets,fill_nans,flag_KEGG_ids)
mrl_kinetics_to_sbtab s = mrl_kinetics_to_sbtab(network, kinetics, quantity_info, save_quantities, file_basename)
sbtab_to_modular_rate_law [kinetics, sbtab_table] = sbtab_to_modular_rate_law(network,file_kinetic_data,options)
network_add_reaction network = network_add_reaction(network,reactants,stoich_coeffs,name,reversible);
network_add_transport network = network_add_transport(network, metabolites,flag_only_reactions);
network_build_from_sum_formulae network = network_build_from_sum_formulas(filename_reactions,filename_compounds,columns)
cobra_to_network [network, ind_keepm, ind_keepr] = cobra_to_network(model,options)
network_sbml_import [network,s] = network_sbml_import(s,dirname,verbose)
find_external_metabolite index = find_external_metabolite(network, metabolite)
network_find_metabolites indices = network_find_metabolites(network,metabolite)
network_find_reactions indices = network_find_reactions(network,metabolites)
network_find_reactions_by_name ind = network_find_reactions_by_name(network,actions)
network_indices [ind_met,ind_act] = network_indices(network)
network_integrate [t, s, s_int, met_int,v,x_assign] = network_integrate(network, s_init, T, graphics_flag, verbose_flag,Tmax,dilution_rate,ode_opt)
network_integrate_par_pert [t, s, v, p, s_int, met_int] = network_integrate_par_pert(network, s, T, gf, par_osc, dt)
annotate_list if key occurs several times in file,
find_metabolites_by_name
SOURCE CODE
% function [label,indices] = label_names(names,allnames, method)
% method 'multiple'
function [label,indices] = label_names(names,allnames,method)
if isstr(names), names = {names}; end
case_sensitive=0;
if not(case_sensitive), names=upper(names); allnames=upper(allnames); end
if ~exist('method'), method = 'single'; end
switch method
 case 'multiple'
 label = cell(length(names),1);
 for k=1:length(names)
  hits = find(strcmp(allnames,names(k)));
  if length(hits)>0
    label{k} = hits;
  end
 end
case 'single'
 label = zeros(length(names),1);
 for k=1:length(names)
  hits = find(strcmp(allnames,names(k)));
  if length(hits)>0
    label(k) = hits(1);
  end
 end
case 'fields'
    allnames=strrep(allnames,'-','_');
    allnames=strrep(allnames,'/','_');
    allnames=strrep(allnames,'.','_');
    names=strrep(names,'-','_');
    names=strrep(names,'/','_');
    names=strrep(names,'.','_');
   indices=struct('a','');
   for i=1:length(allnames),
      allnames{i}
     eval(['indices.' allnames{i} '=' num2str(i) ';']);
  end
  label=zeros(length(names),1);
  for k=1:length(names)
     if isfield(indices,names{k}),
       label(k) = getfield(indices,names{k});
     end
  end
end