Description of listbox
Home > mnt > utils > listbox.m
listbox
PURPOSE
[indices,h] = listbox(list,indices);
SYNOPSIS
function [indices,h] = listbox(list,indices);
DESCRIPTION
 [indices,h] = listbox(list,indices);
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
network_choose_from_list [n_sub,metindices_chosen,metindices,actindes] = network_choose_from_list(network,metnames,indices)
network_listchoose_actions [n_sub,actindices] = network_listchoose_actions(network,actnames,indices)
network_listchoose_metabolites [n_sub,metindices] = network_listchoose_metabolites(network,metnames,indices)
network_choose_reactions_from_list [n_sub,actindices_chosen,metindices,actindes] = network_choose_from_list(network,actnames,indices)
SOURCE CODE
% [indices,h] = listbox(list,indices);
function [indices,h] = listbox(list,indices);
if ~exist('indices','var'), indices = []; end
cell_array = cellstr([ num2str((1:length(list))') repmat(' | ',length(list),1) char(list)])';
clf;
h = uicontrol('style','list','max',10,'min',1,'Position',[10 10 500 400],'string',cell_array,'Value',indices);
fprintf('Choose items and then press any key to confirm.\nYou can use the control key to choose several items\n');
pause;
indices = get(h,'Value');
clf;