Description of lognormal_log2normal
Home > mnt > utils > lognormal_log2normal.m
lognormal_log2normal
PURPOSE
[mu,sigma] = lognormal_log2normal(mu_log,sigma_log,convention)
SYNOPSIS
function [mu,sigma] = lognormal_log2normal(mu_log,sigma_log,convention)
DESCRIPTION
 [mu,sigma] = lognormal_log2normal(mu_log,sigma_log,convention)
 convert mean and std dev of Gaussian random variable into
 characteristics of random variable Y = exp(X)
 convention 'arithmetic': mean and std dev of Y
 convention 'geometric':  geometric mean and spread = geom.mean * (geom.std.dev - 1 ) of Y
CROSS-REFERENCE INFORMATION
This function calls:
default commandstring = default(varname1,defaultvalue1,varname2,defaultvalue2,...)
This function is called by:
data_integration_bounds_pseudovalues kinetic_data = data_integration_bounds_pseudovalues(kinetic_data,quantity_info,flag_pseudo_values,network);
data_integration_load_kinetic_data kinetic_data = data_integration_load_kinetic_data(data_quantities, quantity_info, network, file_kinetic_data, use_sbml_ids, use_kegg_ids, flag_invent_std, verbose)
parameter_balancing [res, exitflag] = parameter_balancing(task, quantity_info, options)
parameter_balancing_task Prepare vectors and matrices for parameter balancing
convert_G_to_kG [kG,kG_std] = convert_G_to_kG(G,RT,G_std)
SOURCE CODE
function [mu,sigma] = lognormal_log2normal(mu_log,sigma_log,convention)
% [mu,sigma] = lognormal_log2normal(mu_log,sigma_log,convention)
%
% convert mean and std dev of Gaussian random variable into
% characteristics of random variable Y = exp(X)
% convention 'arithmetic': mean and std dev of Y
% convention 'geometric':  geometric mean and spread = geom.mean * (geom.std.dev - 1) of Y
eval(default('convention','lognormal_standard_convention'));
switch convention,
  case 'geometric',
    mu    = exp(mu_log);
    sigma = mu .* (exp(sigma_log)-1);
  case 'arithmetic',
    mu     = exp( mu_log +  1/2 * sigma_log.^2 );
    mu(isnan(sigma_log)) = exp(mu_log(isnan(sigma_log)));
    sigma  = sqrt(( exp(sigma_log.^2) - 1).* exp(2* mu_log + sigma_log.^2));
end
% test
%
%mu=10;sigma =1;
%convention = 'geometric';
%[mu_log,sigma_log] = lognormal_normal2log(mu,sigma,convention);
%[mu,sigma] = lognormal_log2normal(mu_log,sigma_log,convention)