Description of lognormal_normal2log
Home > mnt > utils > lognormal_normal2log.m
lognormal_normal2log
PURPOSE
function [mu_log,sigma_log] = lognormal_normal2log(mu,sigma,convention)
SYNOPSIS
function [mu_log,sigma_log] = lognormal_normal2log(mu,sigma,convention)
DESCRIPTION
 function [mu_log,sigma_log] = lognormal_normal2log(mu,sigma,convention)
 convert characteristics of log-normal random variable  X
 into mean and std dev of random variable Y = log(X)
 characteristics are given by:
  convention 'arithmetic': mean and std dev
  convention 'geometric': geometric mean and spread = geom.mean * (geom.std.dev - 1 )
CROSS-REFERENCE INFORMATION
This function calls:
default commandstring = default(varname1,defaultvalue1,varname2,defaultvalue2,...)
This function is called by:
data_integration_load_kinetic_data kinetic_data = data_integration_load_kinetic_data(data_quantities, quantity_info, network, file_kinetic_data, use_sbml_ids, use_kegg_ids, flag_invent_std, verbose)
convert_kG_to_G [G,G_std] = convert_kG_to_G(kG,rt,kG_std)
ms_import_kinetic [kin_data,parameter_prior] = ms_import_kinetic(network,kinetic_balanced_file)
parameter_balancing_sbtab a wrapper for parameter balancing that reads all input data (model, priors, kinetic and metabolic data)
SOURCE CODE
function [mu_log,sigma_log] = lognormal_normal2log(mu,sigma,convention)
% function [mu_log,sigma_log] = lognormal_normal2log(mu,sigma,convention)
%
% convert characteristics of log-normal random variable  X
% into mean and std dev of random variable Y = log(X)
% characteristics are given by:
%  convention 'arithmetic': mean and std dev
%  convention 'geometric': geometric mean and spread = geom.mean * (geom.std.dev - 1)
eval(default('convention','lognormal_standard_convention'));
switch convention,
  case 'geometric',
    mu_log    = log(mu);
    sigma_log = log(sigma./mu + 1);
  case 'arithmetic',
    ind = find(mu<10^-14);
    if ind,
      mu(ind)= 10^-14;
      warning('Log-normal distribution with very small mean value encountered');
    end
    mu_log     = log(mu) - 1/2 * log(1+(sigma./mu).^2);
    mu_log(isnan(sigma)) = log(mu(isnan(sigma)));
    sigma_log  = sqrt(log(1 + ( sigma ./ mu).^2));
end