Description of matrix_add_block
Home > mnt > utils > matrix_add_block.m
matrix_add_block
PURPOSE
M = matrix_add_block(A,B);
SYNOPSIS
function M = matrix_add_block(A,B);
DESCRIPTION
M = matrix_add_block(A,B);
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
flux2entropy_production [mu,A,R] = flux2entropy_production(network,v,mu_ext)
optimise_delta_mu_given_signs delta_mu = optimize_delta_mu_given_signs(N,parameter_prior,data,v,options)
optimise_mu_given_signs [delta_mu,delta_mu_score,this_mu] = optimize_mu_given_signs(N,parameter_prior,data,v,options,constraints)
SOURCE CODE
function M = matrix_add_block(A,B);
%M = matrix_add_block(A,B);
if issparse(A), A = full(A); end
if issparse(B), B = full(B); end
M= zeros(size(A,1)+size(B,1),size(A,2)+size(B,2));
M(1:size(A,1),1:size(A,2)) = A;
M(size(A,1)+1:size(A,1)+size(B,1),size(A,2)+1:size(A,2)+size(B,2)) = B;
M=sparse(M);