Description of noticks
Home > mnt > utils > noticks.m
noticks
PURPOSE
noticks();
SYNOPSIS
function noticks();
DESCRIPTION
 noticks();
 remove axis ticks
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
model_reduction_draw_figures info = model_reduction_draw_figures(network,r,tF,s_tF,tR,s_tR,x_tR,tE,s_tE,weights,Tr,metabolites_subsystem,subsystem2_metabolites,gp,network_CoHid)
display_expression [Delta_logS_mean,Delta_logJ_mean,Delta_logS_cov,Delta_logJ_cov] = display_expression(network,solution1,solution2,d1,d2)
flux_direction_probs [prob, mean_prob, var_prob] = flux_direction_probs(network, solution, fn);
display_stochastic_control display_stochastic_control(network,solution,control_type,direction_type,ind,filename)
display_variability
make_pictures
netgraph_draw netgraph_draw(network,varargin)
netgraph_move2 network = netgraph_move2(network,flag_draw_details)
SOURCE CODE
% noticks();
% remove axis ticks
function noticks();
set(gca,'XTick',[]);
set(gca,'YTick',[]);
set(gca,'ZTick',[]);