Description of rb_colors
Home > mnt > utils > rb_colors.m
rb_colors
PURPOSE
c = rb_colors(ncol)
SYNOPSIS
function c = rb_colors(ncol)
DESCRIPTION
 c = rb_colors(ncol)
CROSS-REFERENCE INFORMATION
This function calls:
default commandstring = default(varname1,defaultvalue1,varname2,defaultvalue2,...)
This function is called by:
interaction_network_plot interaction_network_plot(network, reaction_values, reaction_pair_values, col, gp)
netgraph_draw netgraph_draw(network,varargin)
SOURCE CODE
function c = rb_colors(ncol)
% c = rb_colors(ncol)
eval(default('ncol','250'));
ncol = ceil(ncol/2);
c = [ repmat([0 0 1],ncol,1) + (0: 1/[ncol-1]:1)' * [1 1 0]; ...
      repmat([1 0 0],ncol,1) + (1:-1/[ncol-1]:0)' * [0 1 1] ] ;
c = flipud(c);
if sum(c(:)<0)
  error('Negative values encountered')
  c(c<0) = 0;
end
c(find(prod(double(c==1),2)),:) = 0.999;