Description of table
Home > mnt > utils > table.m
table
PURPOSE
result = table(names,rownumbers,filename)
SYNOPSIS
function res = table(names,rownumbers,filename)
DESCRIPTION
result = table(names,rownumbers,filename)
display cell array of strings to file
flag rownumbers: 0 (none), 1 (yes) ,'tex' (tex style)
(if filename is given -> output to file)
CROSS-REFERENCE INFORMATION
This function calls:
default commandstring = default(varname1,defaultvalue1,varname2,defaultvalue2,...)
This function is called by:
data_integration_display_kinetic_data T = data_integration_display_kinetic_data(kinetic_data,network,flag_display)
data_integration_save_kinetic_data M = data_integration_save_kinetic_data(kinetic_data,network,filename,options_style)
netgraph_assign_positions xpos = netgraph_assign_positions(network,picture,offsets,outfile)
mrl_kinetics_to_sbtab s = mrl_kinetics_to_sbtab(network, kinetics, quantity_info, save_quantities, file_basename)
network_build_from_sum_formulae network = network_build_from_sum_formulas(filename_reactions,filename_compounds,columns)
network_list_allosteric network_list_allosteric(network)
network_print_conservation_relations network_print_conservation_relations(network,G)
print_matrix b = print_matrix(matrix,rownames,colnames)
SUBFUNCTIONS
function res = str(text)
SOURCE CODE
%result = table(names,rownumbers,filename)
%
%display cell array of strings to file
%flag rownumbers: 0 (none), 1 (yes) ,'tex' (tex style)
%(if filename is given -> output to file)
function res = table(names,rownumbers,filename)
eval(default('rownumbers','1','filename','[]'));
[nlines,nfields] = size(names);
res = '';
if nlines*nfields == 0, warning('Empty table'); end
switch rownumbers,
  case 0,
    for k=1:nlines
      for l=1:nfields-1
        res = [res, sprintf('%s\t',str(names{k,l}))];
      end
      res = [res, sprintf('%s\n', str(names{k,nfields}))];
    end
  case 'tex',
    for k=1:nlines
      for l=1:nfields-1
        res = [res, sprintf('%s \& ',str(names{k,l}))];
      end
      res = [res, sprintf('%s\\\\\n',str(names{k,nfields}))];
    end
  otherwise,
    for k=1:nlines
      res = [res, sprintf('%d\t',k)];
      for l=1:nfields-1
        res = [res, sprintf('%s\t',str(names{k,l}))];
      end
      res = [res, sprintf('%s\n', str(names{k,nfields}))];
    end
end
if ~isempty(filename),
  file = fopen(filename,'w');
  fprintf(file,'%s',res);
  fclose(file);
end
% ----------------------------------------------------------------------
function res = str(text)
if iscell(text),
  res = text{1};
  for i=2:length(text), res=[res char(9) text{i}]; end
elseif isnumeric(text),
  res = num2str(text,3);
else,
  res = char(text);
end