Description of tensor_scale
Home > mnt > utils > tensor_scale.m
tensor_scale
PURPOSE
U = tensor_scale(T,k,x);
SYNOPSIS
function U = tensor_scale(T,k,x);
DESCRIPTION
U = tensor_scale(T,k,x);
 calculate U_(ab..i..lm) = sum_i T_(ab..i..lm) * x_i
 where i is the kth index of T
CROSS-REFERENCE INFORMATION
This function calls:
tensor_product C = tensor_product(A,B,index_A,index_B)
tensor_scale U = tensor_scale(T,k,x);
This function is called by:
norm_response_coefficients [RS_norm,RJ_norm,RS2_norm,RJ2_norm] = norm_response_coefficients(s,j,p,RS,RJ,RS2,RJ2,used_J)
second_derivative_scaled2unscaled D2_un = second_derivative_scaled2unscaled(D2_sc,D_sc,f,x)
second_derivative_unscaled2scaled D2_sc = second_derivative_unscaled2scaled(D2_un,D_un,f,x)
tensor_scale U = tensor_scale(T,k,x);
SOURCE CODE
function U = tensor_scale(T,k,x);
%U = tensor_scale(T,k,x);
%
% calculate U_(ab..i..lm) = sum_i T_(ab..i..lm) * x_i
% where i is the kth index of T
n_dims = length(size(T));
TT     = tensor_product(T,diag(x),k,1);
U      = permute(TT,[1:k-1, n_dims, k:n_dims-1]);
return
% test
A = ones(1,2,3);
B = [2,3];
C = [3,4,5];
tensor_scale(tensor_scale(tensor_scale(tensor_scale(A,2,B),3,C),1,1./B),2,1./C)