Description of demo_small_network
Home > demo > demo_small_network.m
demo_small_network
PURPOSE
DEMO_SMALL_NETWORK - Demo for Metabolic Network Toolbox
SYNOPSIS
This is a script file.
DESCRIPTION
DEMO_SMALL_NETWORK - Demo for Metabolic Network Toolbox
CROSS-REFERENCE INFORMATION
This function calls:
netgraph_draw netgraph_draw(network,varargin)
netgraph_external [network,p] = netgraph_external(network,draw_only,external)
netgraph_move network = netgraph_move(network,flag_draw_details,options,picture,filename_in,filename_out)
netgraph_movie [M,T] = netgraph_movie(network,t,s_t,data_type,n_frames,text_flag,options);
netgraph_reversible [network,p] = netgraph_reversible(network)
set_kinetics kinetics = set_kinetics(network,type,parameters)
analyse_N [ K, L, NR, null_l, pinv_NR, independent_metabolites, N1] = analyse_N(N,external)
control_coefficients [CJ, CS, L_int, NR_int, M, indp_among_internal] = control_coefficients(N, Ec, external, used, NR_int, L_int, indp_among_internal,dilution_rate)
elasticities [Ec,Ep,parameters,Ecc,Ecp,Epp,p] = elasticities(network,s,options);
time_response_coefficients [t, s, RS, s_ind, RS_ind, parameters, par_names]= time_response_coefficients(network, s0, t_final)
network_construct network = network_construct(N,reversible,ind_external,metabolites,actions,no_graphics,regulation_matrix)
network_integrate [t, s, s_int, met_int,v,x_assign] = network_integrate(network, s_init, T, graphics_flag, verbose_flag,Tmax,dilution_rate,ode_opt)
network_steady_state [S, J, Sdot, error] = network_steady_state(network,s,integrate_time,L_int,NR_int,indep_met_int,dilution_rate)
This function is called by:
SOURCE CODE
%DEMO_SMALL_NETWORK - Demo for Metabolic Network Toolbox
echo on;
clc
% We consider the following simple network
%
% S1             S5
%    \         /
%      S3 - S4
%    /         \
% S2             S6
%
% (where Sn denotes metabolites) to illustrate some
% of the functions of the Metabolic Network Toolbox.
%
% Please hit any key to continue
pause
clc
% We define the network by its stoichiometric matrix N,
% the reversibility of reactions (bit string)
% and the external metabolites (indices)
%
N            = [ -1 0 0 0 0; ...
         0 -1 0 0 0; ...
         1 1 -1 0 0; ...
         0 0 1 -1 -1; ...
         0 0 0 1 0; ...
         0 0 0 0 1];
reversible   = [1 1 1 1 1]';
external_ind = [1 2 5 6 ]';
%
% Hit any key to continue
pause
% All information about the network is then stored in a matlab structure
network      = network_construct(N,reversible,external_ind)
% The fields 'kinetics' and 'graphics_par' contain information
% about reaction kinetics and the graphical layout (set here by default).
% Hit any key to continue
pause
clc
% The functions in the 'netgraph' directory change the layout
% of the network (defined by the field 'graphics_par').
% The command "netgraph_move" allows you to move the nodes
% with your mouse (press right mouse key to quit)
network = netgraph_move(network);
% We can set/remove the reversible reactions ...
%
network = netgraph_reversible(network);
% ... and the external metabolites
%
network = netgraph_external(network);
clc
clf
% Now we analyse the network structure
% Information about stationary fluxes and conservation
% relations can be obtained from the kerbel matrix K
% and the link matrix L (for the stoichimetric matrix
% of internal metabolites)
[ K, L ] = analyse_N(N(find(network.external==0),:))
% Hit any key to continue
pause
clc
% Until here, we only considered the network structure.
% Now we define a kinetics.
% There are different ways to specify a kinetics (see 'kinetics_structure').
% Here we choose a common modular rate law kinetics for all reactions.
%
network.kinetics = set_kinetics(network,'cs');
% This updates the field 'kinetics', which contains all kinetic data.
%
% Hit any key to continue
pause
clc
% Now we can run dynamical simulations.
% First, we compute a stationary state, starting from an initial guess
% of the concentrations ...
s = [1 1 0 0 0 0]';
[S, J] = network_steady_state(network,s);
% ... and plot it on the network graph.
%
netgraph_draw(network,'metvalues',S,'arrowvalues',J,'arrowstyle','fluxes');
% The size (and color) of octagons
% and squares represents the values of concentrations and fluxes.
%
% Hit any key to continue
pause
clc
% Likewise, we can compute properties from metabolic control analysis,
% for instance, elasticity coefficients and control coefficients
% (for more information: type 'help control_theory')
%
epsilon       = elasticities(network,S);
[ C_J, C_S ]  = control_coefficients(network.N,epsilon,network.external);
% Here we plot the control coefficients on the 4th metabolite
netgraph_draw(network,'actvalues',C_S(4,:)');
% Hit any key to continue
pause
clc
% Metabolic control theory has proven theorems that relate the
% control coefficients to the network structure (described by
% K and L) and the reaction elasticities.
%
% The theorems for non-normalised control coefficients read
%
%Summation theorems
% CJ K         = K
% CS K         = 0
%
%Connectivity theorems
% CJ epsilon L = 0
% CS epsilon L = - L
%
%Let us check them:
%
% CJ K = K
C_J*K
K
pause
% CS K = 0
C_S(find(network.external==0),:)*K
pause
% CJ epsilon L = 0
C_J(find(network.external==0),:)*epsilon(:,find(network.external==0))*L
pause
% CS epsilon L = - L
C_S(find(network.external==0),:)*epsilon(:,find(network.external==0))*L
L
pause
clc
% We compute a time course with initial conditions given by s:
[t,s_t,s_int] = network_integrate(network,s,5);
close
plot(t,s_t)
% Hit any key to continue
pause
% We can also show the time course as a movie
M = netgraph_movie(network,t,s_t);
movie(M,1);
% Hit any key to continue
pause
close
% Accordingly, we can compute time-dependent response coefficients
[t, s_t, RS, s_ind_t, RS_ind, parameters, parameter_names] = time_response_coefficients(network, s, 5);
plot(t,squeeze(RS(:,1,:)))
%
% Enjoy this toolbox!
echo off;