Description of mnt_demo
Home > demo > mnt_demo.m
mnt_demo
PURPOSE
SYNOPSIS
This is a script file.
DESCRIPTION
CROSS-REFERENCE INFORMATION
This function calls:
netgraph_draw netgraph_draw(network,varargin)
netgraph_make_graph network = netgraph_make_graph(network,metvalues,actvalues,set_positions,x_init,table_positionss);
netgraph_movie [M,T] = netgraph_movie(network, t ,s_t, data_type, n_frames, text_flag, options);
set_kinetics kinetics = set_kinetics(network,type,parameters)
analyse_N [ K, L, NR, null_l, pinv_NR, independent_metabolites, N1] = analyse_N(N,external)
control_coefficients [CJ, CS, L_int, NR_int, M, M_adj, indp_among_internal] = control_coefficients(N, Ec, external, used, NR_int, L_int, indp_among_internal,dilution_rate)
elasticities [Ec,Ep,parameters,Ecc,Ecp,Epp,p] = elasticities(network,s,options);
network_construct network = network_construct(N,reversible,ind_external,metabolites,actions,no_graphics,regulation_matrix,flag_kinetics)
network_sbml_export SBMLmodel = network_sbml_export(network, verbose, name, filename, notes, sbml_level, sbml_version)
network_integrate [t, s, s_int, met_int,v,x_assign] = network_integrate(network, s_init, T, graphics_flag, verbose_flag,Tmax,dilution_rate,ode_opt)
network_steady_state [S, J, Sdot, error] = network_steady_state(network,s,integrate_time,L_int,NR_int,indep_met_int,dilution_rate)
mnt_dependencies
This function is called by:
SOURCE CODE
data_dir = [fileparts(which(mfilename)) '/data'];
mnt_dependencies;
echo on;
clc
%----------------------------------------------
% MNT_DEMO - Demo for Metabolic Network Toolbox
%
% In this demo, a small metabolic network is
% built from its stoichiometric matrix,
% analysed by Metabolic Control Analysis,
% and a time simulation is run.
%----------------------------------------------
% Please press any key to continue
pause
clc
%----------------------------------------------
% We consider the following simple network
% S1             S5
%    \         /
%      S3 - S4
%    /         \
% S2             S6
% to illustrate some functions of the Metabolic Network Toolbox.
% Please press any key to continue
pause
clc
%----------------------------------------------
% We first need to define the network.
% This is done by the stoichiometric matrix N,
% the reversibility of reactions (as a bit column),
% and the indices of external metabolites
N = [ -1  0  0  0  0; ...
       0 -1  0  0  0; ...
       1  1 -1  0  0; ...
       0  0  1 -1 -1; ...
       0  0  0  1  0; ...
       0  0  0  0  1];
reversible   = [1 1 1 1 1]';
ind_external = [1 2 5 6 ]';
network = network_construct(N, reversible, ind_external);
% Press any key to continue
pause
clc
%----------------------------------------------
% All information about the network is now stored in the structure
network
% The fields 'kinetics' and 'graphics_par' contain information
% about reaction kinetics and the graphical layout (set here by default).
% The following command draws the network
figure(1);
netgraph_draw(network);
% The arrows indicate the nominal reaction directions.
% Press any key to continue
pause
clc
%----------------------------------------------
% Now we will analyse the network structure.
% Information about stationary fluxes and conservation relations
% can be obtained from the kernel matrix K and the link matrix L.
% Both follow from the stoichimetric matrix of internal metabolites.
[K, L] = analyse_N(N(find(network.external==0),:))
% Press any key to continue
pause
clc
%----------------------------------------------
% Until here, we only considered the network structure.
% Kinetic rate laws can be stored in the field 'network.kinetics'.
% There are different ways to specify them (see 'kinetics_structure').
% This is how we choose common modular rate laws for all reactions.
network.kinetics = set_kinetics(network,'cs');
% Press any key to continue
pause
clc
%----------------------------------------------
% Now we can run dynamical simulations.
% First, we guess an intial set of concentrations ..
s = [1 1 0 0 0 0]';
% .. compute stationary concentrations and fluxes ..
[S, J] = network_steady_state(network,s);
% .. and plot them on the network graph.
network = netgraph_make_graph(network);
figure(2);
netgraph_draw(network,{'metvalues',S,'arrowvalues',J,'arrowstyle','fluxes'});
% The circles and squares represent metabolites and reactions.
% Press any key to continue
pause
clc
%---------------------------------------------------------------------
% Likewise, we can compute elasticity and control coefficients
% (for information on metabolic control analysis, type 'help mnt_mca')
epsilon     = elasticities(network,S);
[C_J, C_S]  = control_coefficients(network.N,epsilon,network.external);
% Here we plot the control coefficients on the 4th metabolite on the network
figure(3);
netgraph_draw(network,'actvalues',C_S(4,:)');
% Press any key to continue
pause
clc
%---------------------------------------------------------------------
% Metabolic control theory has proven theorems that relate the
% control coefficients to the network structure (described by
% K and L) and the reaction elasticities.
% Summation theorems
%  CJ * K  = K
%  CS * K  = 0
% Connectivity theorems
%  CJ * epsilon * L = 0
%  CS * epsilon * L = - L
% We will now check if our control coefficients satisfy them
% In the theorems, we consider only the elasticities and concentration
% control matrices with respect to internal metabolites
ind_internal = find(network.external==0);
epsilon_int  = epsilon(:,ind_internal);
C_S_int      = C_S(ind_internal,:);
% Press any key to continue
pause
clc
%---------------------------------------------------------------------
% Since CJ K = K, the following should vanish:
C_J * K - K
% Press any key to continue
pause
clc
%---------------------------------------------------------------------
% Since CS K = 0, the following should vanish:
C_S_int * K
% Press any key to continue
pause
clc
%---------------------------------------------------------------------
% Since CJ epsilon L = 0, the following should vanish:
C_J * epsilon_int * L
% Press any key to continue
pause
clc
%---------------------------------------------------------------------
% Since CS epsilon L = - L, the following should vanish:
C_S_int * epsilon_int * L + L
% Press any key to continue
pause
clc
%---------------------------------------------------------------------
% Now we compute a time course, with initial conditions given by s:
[t,s_t,s_int] = network_integrate(network,s,5);
figure(4); plot(t,s_t)
% Press any key to continue
pause
% --------------------------------------------------------------------
% We can also show the time course as a movie
M = netgraph_movie(network,t,s_t);
figure(4);
movie(M,1);
% Press any key to continue
pause
% --------------------------------------------------------------------
% Finally, we can export the model to SBML format
SBMLmodel = network_sbml_export(network,1);
% Press any key to finish
pause
% Enjoy this toolbox!
echo off;