Description of eba_my_cycles
Home > mnt > mnt_fluxes > eba > eba_util > eba_my_cycles.m
eba_my_cycles
PURPOSE
wrapper around 'cycles', allowing to ignore some reactions
SYNOPSIS
function C = eba_my_cycles(N,C,ind_ignore)
DESCRIPTION
 wrapper around 'cycles', allowing to ignore some reactions
CROSS-REFERENCE INFORMATION
This function calls:
cycles C = cycles(N);
This function is called by:
eba_make_feasible v = eba_make_feasible(v,N,eba_condition,C,ind_ignore)
feasible_fluxes [v, C] = feasible_fluxes(N,ind_ext,data,es_constraints,eba_condition,C)
eba_feasible [feasible,C,ind_non_orthogonal] = eba_feasible(v,N,C,ind_ignore,eba_condition,cycle_method)
SOURCE CODE
function C = eba_my_cycles(N,C,ind_ignore)
% wrapper around 'cycles', allowing to ignore some reactions
if isnan(C),
  if ind_ignore,
    use_in_cycles = setdiff(1:size(N,2),ind_ignore);
    NN = N(:,use_in_cycles);
    CC = cycles(NN);
    C  = zeros(size(N,2),size(CC,2));
    C(use_in_cycles,:) = CC;
  else,
    C = cycles(N);
  end
end