Description of eba_feasible
Home > mnt > mnt_fluxes > flux_feasibility > eba_feasible.m
eba_feasible
PURPOSE
[feasible,C,ind_non_orthogonal] = eba_feasible(v,N,C,ind_ignore,eba_condition,cycle_method)
SYNOPSIS
function [feasible,C,ind_non_orthogonal] = eba_feasible(v,N,C,ind_ignore,eba_condition,cycle_method)
DESCRIPTION
 [feasible,C,ind_non_orthogonal] = eba_feasible(v,N,C,ind_ignore,eba_condition,cycle_method)
 wrapper function for Energy Balance Analysis:
 test a flux vector v for EBA feasibility using cycles (=elementary modes of N)
 with stoichiometric matrix N (for all metabolites)
 ind_ignore: reactions to be ignored in the cycle constraints
CROSS-REFERENCE INFORMATION
This function calls:
EBA_loosely_orth orthogonal = EBA_orth(sign_J,C)
EBA_orth orthogonal = EBA_orth(sign_J,C)
EBA_orth orthogonal = EBA_orth(sign_J,C)
eba_my_cycles wrapper around 'cycles', allowing to ignore some reactions
network_efmtool [C,mnet] = network_efmtool(network, method, ind_ignore, zv)
network_construct network = network_construct(N,reversible,ind_external,metabolites,actions,no_graphics,regulation_matrix,flag_kinetics)
default commandstring = default(varname1,defaultvalue1,varname2,defaultvalue2,...)
This function is called by:
eba_make_feasible v = eba_make_feasible(v,N,eba_condition,C,ind_ignore)
eba_feasible_lp [eba_feasible, dmu] = eba_feasible(v,Ntot,dmu_fix,rho,epsilon,dmu_limit)
es_check_flux_constraints isFeasible = es_check_flux_constraints(v,N,ind_ext,constraints,verbose,epsilon_stationary,C)
project_fluxes v_projected = project_fluxes(N,ind_ext, v_mean, v_std, v_sign, pars);
sample_fluxes_given_data [sample_v, best_v, C] = sample_fluxes_given_data(N, ind_ext, v_mean, v_std, n_sample_v, n_recombine_v, seed, ind_ignore, v_sign);
SOURCE CODE
function [feasible,C,ind_non_orthogonal] = eba_feasible(v,N,C,ind_ignore,eba_condition,cycle_method)
% [feasible,C,ind_non_orthogonal] = eba_feasible(v,N,C,ind_ignore,eba_condition,cycle_method)
%
% wrapper function for Energy Balance Analysis:
% test a flux vector v for EBA feasibility using cycles (=elementary modes of N)
%
% with stoichiometric matrix N (for all metabolites)
%
% ind_ignore: reactions to be ignored in the cycle constraints
eval(default('C','nan','ind_ignore','[]','eba_condition','''loose''','cycle_method','''efmtool'''));
if isnan(C),
  display('Computing elementary cycles. This may take a while');
  switch cycle_method,
    case 'beard',
      C = eba_my_cycles(N,C,ind_ignore);
    case 'efmtool',
      [nm,nr] = size(N);
      network = network_construct(full(N),ones(nr,1),[]);
      C = network_efmtool(network,'total',ind_ignore);
  end
end
switch eba_condition,
  case 'strict', [feasible,ind_non_orthogonal] = EBA_orth(sign(v),C);
  case 'loose',  [feasible,ind_non_orthogonal] = EBA_loosely_orth(sign(v),C);
end