Description of char
Home > mnt > util > xml > xmltree > @xmltree > char.m
char
PURPOSE
XMLTREE/CHAR Converter function from XMLTree to a description string
SYNOPSIS
function s = char(tree)
DESCRIPTION
 XMLTREE/CHAR Converter function from XMLTree to a description string
 FORMAT s = char(tree)
 tree - XMLTree object
 s    - a description string of an XMLTree
_______________________________________________________________________
 Return a string describing the XMLTree:
               'XMLTree object (x nodes) [filename]'
_______________________________________________________________________
 @(#)char.m                   Guillaume Flandin               02/04/04
CROSS-REFERENCE INFORMATION
This function calls:
getfilename XMLTREE/GETFILENAME Get filename method
length XMLTREE/LENGTH Length Method
This function is called by:
display XMLTREE/DISPLAY Command window display of an XMLTree
SOURCE CODE
function s = char(tree)
% XMLTREE/CHAR Converter function from XMLTree to a description string
% FORMAT s = char(tree)
%
% tree - XMLTree object
% s    - a description string of an XMLTree
%_______________________________________________________________________
%
% Return a string describing the XMLTree:
%               'XMLTree object (x nodes) [filename]'
%_______________________________________________________________________
% @(#)char.m                   Guillaume Flandin               02/04/04
s = strcat('XMLTree object (',num2str(length(tree)),' nodes) [',getfilename(tree),']');