Description of isfield
Home > mnt > util > xml > xmltree > @xmltree > isfield.m
isfield
PURPOSE
XMLTREE/ISFIELD Is parameter a field of tree{uid} ?
SYNOPSIS
function F = isfield(tree,uid,parameter)
DESCRIPTION
 XMLTREE/ISFIELD Is parameter a field of tree{uid} ?
 FORMAT F = isfield(tree,uid,parameter)
 tree      - a tree
 uid       - uid of the element
 parameter - a field of the root tree
 F         - 1 if present, 0 otherwise
_______________________________________________________________________
 Is parameter a field of tree{uid} ?
_______________________________________________________________________
 @(#)isfield.m               Guillaume Flandin                01/10/31
CROSS-REFERENCE INFORMATION
This function calls:
isfield XMLTREE/ISFIELD Is parameter a field of tree{uid} ?
length XMLTREE/LENGTH Length Method
This function is called by:
add XMLTREE/ADD Method (add childs to elements of an XML Tree)
branch XMLTREE/BRANCH Branch Method
convert XMLTREE/CONVERT Converter an XML tree in a Matlab structure
copy XMLTREE/COPY Copy Method (copy a subtree in another branch)
delete XMLTREE/DELETE Delete (delete a subtree given its UID)
find XMLTREE/FIND Find elements in a tree with specified characteristics
flush XMLTREE/FLUSH Flush (Clear a subtree given its UID)
isfield XMLTREE/ISFIELD Is parameter a field of tree{uid} ?
SOURCE CODE
function F = isfield(tree,uid,parameter)
% XMLTREE/ISFIELD Is parameter a field of tree{uid} ?
% FORMAT F = isfield(tree,uid,parameter)
%
% tree      - a tree
% uid       - uid of the element
% parameter - a field of the root tree
% F         - 1 if present, 0 otherwise
%_______________________________________________________________________
%
% Is parameter a field of tree{uid} ?
%_______________________________________________________________________
% @(#)isfield.m               Guillaume Flandin                01/10/31
error(nargchk(3,3,nargin));
F = zeros(1,length(uid));
for i=1:length(uid)
    if isfield(tree.tree{uid(i)},parameter)
        F(i) = 1;
    end
end