Description of length
Home > mnt > util > xml > xmltree > @xmltree > length.m
length
PURPOSE
XMLTREE/LENGTH Length Method
SYNOPSIS
function l = length(tree,r)
DESCRIPTION
 XMLTREE/LENGTH Length Method
 FORMAT l = length(tree,r)
 tree - XMLTree object
 r    - 'real' if present, returns the real number of nodes in the
         tree (deleted nodes aren't populated)
 l    - length of the XML tree (number of nodes)
_______________________________________________________________________
 Return the number of nodes of an XMLTree object.
_______________________________________________________________________
 @(#)length.m                 Guillaume Flandin               02/03/27
CROSS-REFERENCE INFORMATION
This function calls:
length XMLTREE/LENGTH Length Method
This function is called by:
add XMLTREE/ADD Method (add childs to elements of an XML Tree)
attributes XMLTREE/ATTRIBUTES Method (handle attributes of an element node)
branch XMLTREE/BRANCH Branch Method
char XMLTREE/CHAR Converter function from XMLTree to a description string
children XMLTREE/CHILDREN Return children's UIDs of node uid
convert XMLTREE/CONVERT Converter an XML tree in a Matlab structure
copy XMLTREE/COPY Copy Method (copy a subtree in another branch)
delete XMLTREE/DELETE Delete (delete a subtree given its UID)
display XMLTREE/DISPLAY Command window display of an XMLTree
find XMLTREE/FIND Find elements in a tree with specified characteristics
flush XMLTREE/FLUSH Flush (Clear a subtree given its UID)
get XMLTREE/GET Get Method (get object properties)
isfield XMLTREE/ISFIELD Is parameter a field of tree{uid} ?
length XMLTREE/LENGTH Length Method
root XMLTREE/ROOT Root Method
save XMLTREE/SAVE Save an XML tree in an XML file
set XMLTREE/SET Method (set object properties)
SOURCE CODE
function l = length(tree,r)
% XMLTREE/LENGTH Length Method
% FORMAT l = length(tree,r)
%
% tree - XMLTree object
% r    - 'real' if present, returns the real number of nodes in the
%         tree (deleted nodes aren't populated)
% l    - length of the XML tree (number of nodes)
%_______________________________________________________________________
%
% Return the number of nodes of an XMLTree object.
%_______________________________________________________________________
% @(#)length.m                 Guillaume Flandin               02/03/27
error(nargchk(1,2,nargin));
% Return the full number of nodes once allocated
l = length(tree.tree);
% Substract the number of deleted nodes to the previous length
if nargin == 2
    if strcmp(r,'real')
        ll = 0;
        for i=1:l
            if ~strcmp(tree.tree{i}.type,'deleted')
                ll = ll + 1;
            end
        end
        l = ll;
    else
        error('[XMLTree] Bad input argument.');
    end
end