Description of convert_kG_to_G
Home > mnt > mnt_kinetics > convenience > convert_kG_to_G.m
convert_kG_to_G
PURPOSE
[G,G_std] = convert_kG_to_G(kG,rt,kG_std)
SYNOPSIS
function [G,G_std,G_cov] = convert_kG_to_G(kG,rt,kG_std)
DESCRIPTION
 [G,G_std] = convert_kG_to_G(kG,rt,kG_std)
CROSS-REFERENCE INFORMATION
This function calls:
convert_G_scale scale_G = convert_G_scale()
default commandstring = default(varname1,defaultvalue1,varname2,defaultvalue2,...)
lognormal_normal2log function [mu_log,sigma_log] = lognormal_normal2log(mu,sigma,convention)
This function is called by:
convenience_print s = convenience_print(kinetics,n,actions,network)
SOURCE CODE
function [G,G_std,G_cov] = convert_kG_to_G(kG,rt,kG_std)
% [G,G_std] = convert_kG_to_G(kG,rt,kG_std)
eval(default('rt','RT'));
scale_G = convert_G_scale;
if exist('kG_std','var'),
  [G,G_std]  = lognormal_normal2log(kG,kG_std);
   G         = G*rt/scale_G;
   G_std     = G_std*rt/scale_G;
else,
  G = log(kG)*rt/scale_G;
end