Description of convenience_dependent_parameters
Home > mnt > mnt_kinetics > convenience > convenience_dependent_parameters.m
convenience_dependent_parameters
PURPOSE
res = convenience_dependent_parameters(network)
SYNOPSIS
function res = convenience_dependent_parameters(network)
DESCRIPTION
 res = convenience_dependent_parameters(network)
CROSS-REFERENCE INFORMATION
This function calls:
convert_log_g_to_log_q [log_q,log_q_cov] = convert_log_g_to_log_q(log_g,N,RT,log_g_cov)
RT result = RT(temperature)
This function is called by:
convenience_print s = convenience_print(kinetics,n,actions,network)
SOURCE CODE
% res = convenience_dependent_parameters(network)
function res = convenience_dependent_parameters(network)
res.keq       = exp(convert_log_g_to_log_q(log(network.kinetics.g),network.N,RT));
res.kcatplus  = network.kinetics.r .* sqrt(res.keq);
res.kcatminus = network.kinetics.r ./ sqrt(res.keq);
res.vmaxplus  = network.kinetics.E .* res.kcatplus;
res.vmaxminus = network.kinetics.E .* res.kcatminus;