Description of parameters2vector
Home > mnt > mnt_kinetics > kinetics > parameters2vector.m
parameters2vector
PURPOSE
[vector,names,relevant,relevant_reactions,types] = parameters2vector(kinetics,S_ext,S_ext_names,network,split,no_names)
SYNOPSIS
function [vector,names,relevant,relevant_reactions,types] = parameters2vector(kinetics,S_ext,S_ext_names,network,split,no_names)
DESCRIPTION
 [vector,names,relevant,relevant_reactions,types] = parameters2vector(kinetics,S_ext,S_ext_names,network,split,no_names)
CROSS-REFERENCE INFORMATION
This function calls:
convenience2vector [vector,names,types,relevant_reactions] = convenience2vector(kinetics,network,no_names)
mass_action2vector [vector,names,relevant] = mass_action2vector(kinetics,used_fwd,used_bwd,S_ext,S_ext_names)
modular_par2vector [v,names] = modular_par2vector(p,network,no_names)
numeric_par2vector function v=par2vector(p)
default commandstring = default(varname1,defaultvalue1,varname2,defaultvalue2,...)
This function is called by:
network_get_parameter_values [parameter_values,names,types] = network_get_parameter_values(network,s,only_enzyme_levels)
elasticities [Ec,Ep,parameters,Ecc,Ecp,Epp,p] = elasticities(network,s,options);
elasticities_scaled [Ec, Ep, parameters, Ecc, Ecp, Epp] = elasticities_scaled(network,s);
internal_elasticities epsilon = internal_elasticities(network,s,enzyme_factor,relevant_parameters);
response_coefficients_numerical [RS,RJ,RS2,RJ2] = response_coefficients_numerical(network,c,ind_rel_par)
response_coefficients_target_numerical [RZp,RZpp] = response_coefficients_target_numerical(network,c,ind_rel_par,zc,zv)
time_response_coefficients [t, s, RS, s_ind, RS_ind, parameters, par_names]= time_response_coefficients(network, s0, t_final)
SOURCE CODE
% [vector,names,relevant,relevant_reactions,types] = parameters2vector(kinetics,S_ext,S_ext_names,network,split,no_names)
function [vector,names,relevant,relevant_reactions,types] = parameters2vector(kinetics,S_ext,S_ext_names,network,split,no_names)
% no_names is important for speed-up
eval(default('split','0','no_names','0'));
relevant_reactions = [];
types              = [];
switch kinetics.type,
  case 'convenience',
    switch nargout,
      case 1,      vector = convenience2vector(kinetics);
      case {2,3},  [vector,names] = convenience2vector(kinetics,network);
      otherwise,   [vector,names,types,relevant_reactions] = convenience2vector(kinetics,network,no_names);
    end
  case 'numeric',        [vector,names] = numeric_par2vector(kinetics.parameters);
  case 'ms',             [vector,names] = modular_par2vector(kinetics, network, no_names);
  case 'cs',             [vector,names] = modular_par2vector(kinetics, network, no_names);
  case 'ds',             [vector,names] = modular_par2vector(kinetics, network, no_names);
  case 'rp',             [vector,names] = modular_par2vector(kinetics, network, no_names);
  case 'fd',             [vector,names] = modular_par2vector(kinetics, network, no_names);
  case 'mass-action',    [vector,names] = mass_action2vector(kinetics);
  case 'standard',       [vector,names,relevant_reactions] = standard_kinetics2vector(kinetics);
  case 'numeric', vector = kinetics.parameter_values;
                          names  = kinetics.parameters;
  otherwise error('Error: unknown kinetics type');
end
if exist('S_ext','var'),
  if ~strcmp(kinetics.type,'convenience'),
    vector = [vector; S_ext];
    names  = [names;  S_ext_names];
    if nargout>=4,
      external_ind = find(network.external);
      for it =1:length(external_ind),
        rel = [ find(network.N(external_ind(it),:)~=0)'; ...
                find(network.regulation_matrix(:,external_ind(it))~=0) ];
        relevant_reactions = [relevant_reactions; {rel}];
      end
    end
  end
end
relevant           = (1:length(vector))';
if nargout>=4,
  if split,
    nr = length(network.actions);
    for it =1:length(relevant_reactions),
      relevant_reactions{it} = [relevant_reactions{it},relevant_reactions{it}+nr];
    end
  end
end