Description of set_kinetics
Home > mnt > mnt_kinetics > kinetics > set_kinetics.m
set_kinetics
PURPOSE
kinetics = set_kinetics(network,type,parameters)
SYNOPSIS
function kinetics = set_kinetics(network,type,parameters)
DESCRIPTION
 kinetics = set_kinetics(network,type,parameters)
 construct a 'kinetics' field for a metabolic network
 type can be {'mass-action','standard','numeric'}
 depending on the type, this function calls one of the following m-files
  set_mass_action_kinetics
  set_numeric_kinetics
  set_standard_kinetics,
 parameters: structure containing parameters to be used for the kinetics
 the subfields required depend on the kinetics type
 (see the respective functions)
CROSS-REFERENCE INFORMATION
This function calls:
set_convenience_kinetics kinetics = set_convenience_kinetics(network,parameters)
set_mass_action_kinetics kinetics = set_mass_action_kinetics(network,parameters)
set_cs_kinetics kinetics = set_cs_kinetics(network,parameters)
set_ds_kinetics kinetics = set_ds_kinetics(network,parameters)
set_ms_kinetics kinetics = set_ms_kinetics(network,parameters)
set_rp_kinetics kinetics = set_rp_kinetics(network,parameters)
This function is called by:
mnt_demo
netgraph_define_module m = netgraph_define_module(network)
sbtab_to_modular_rate_law [kinetics, sbtab_table] = sbtab_to_modular_rate_law(network,file_kinetic_data,options)
sbtab_to_modular_rate_law_via_kinetic_data [kinetics, kinetic_data] = sbtab_to_modular_rate_law(network,file_kinetic_data,options)
network_construct network = network_construct(N,reversible,ind_external,metabolites,actions,no_graphics,regulation_matrix,flag_kinetics)
SOURCE CODE
% kinetics = set_kinetics(network,type,parameters)
%
% construct a 'kinetics' field for a metabolic network
%
% type can be {'mass-action','standard','numeric'}
% depending on the type, this function calls one of the following m-files
%  set_mass_action_kinetics
%  set_numeric_kinetics
%  set_standard_kinetics,
%
% parameters: structure containing parameters to be used for the kinetics
% the subfields required depend on the kinetics type
% (see the respective functions)
function kinetics = set_kinetics(network,type,parameters)
if ~exist('parameters','var'), parameters = []; end
if ~exist('type','var'),       type = 'mass-action'; end
switch type,
  case 'numeric',          kinetics = set_numeric_kinetics(network,parameters);
  case 'cs',               kinetics = set_cs_kinetics(network,parameters);
  case 'ds',               kinetics = set_ds_kinetics(network,parameters);
  case 'ms',               kinetics = set_ms_kinetics(network,parameters);
  case 'rp',               kinetics = set_rp_kinetics(network,parameters);
  case 'fd',               kinetics = set_fd_kinetics(network,parameters);
  case 'convenience',      kinetics = set_convenience_kinetics(network,parameters);
  case 'mass-action',      kinetics = set_mass_action_kinetics(network,parameters);
  case 'standard',         kinetics = set_standard_kinetics(network,parameters);
  case 'ready_made',       parameters.ready_made = 1; kinetics = set_standard_kinetics(network,parameters);
  otherwise,  error('rate law unknown');
end