Description of make_structure_matrices
Home > mnt > mnt_network > network_query > make_structure_matrices.m
make_structure_matrices
PURPOSE
[Mplus, Mminus, Wplus, Wminus, nm, nr, N_int,ind_M,ind_Wp,ind_Wm] = make_structure_matrices(N,W,ind_ext,h)
SYNOPSIS
function [Mplus, Mminus, Wplus, Wminus, nm, nr, N_int,ind_M,ind_Wp,ind_Wm,ind_Mp,ind_Mm] = make_structure_matrices(N,W,ind_ext,h)
DESCRIPTION
 [Mplus, Mminus, Wplus, Wminus, nm, nr, N_int,ind_M,ind_Wp,ind_Wm] = make_structure_matrices(N,W,ind_ext,h)
CROSS-REFERENCE INFORMATION
This function calls:
default commandstring = default(varname1,defaultvalue1,varname2,defaultvalue2,...)
This function is called by:
compute_cs_elasticities E = compute_cs_elasticities(N, W, ext_ind, alpha_A, alpha_I, alpha_M, vplus, vminus, u, c)
compute_cs_kX_elasticities [E_kX_sc,kX_names,kX] = compute_cs_kX_elasticities(network, c);
compute_ds_elasticities E = compute_ms_elasticities(N, W, ext_ind, alpha_A, alpha_I, alpha_M, vplus, vminus, u, c)
compute_modular_elasticities E = compute_modular_elasticities(kinetic_law, N, W, ind_ext, alpha_A, alpha_I, alpha_M, v, A, u, c, h, v_plus_fallback, v_minus_fallback,flag_second_order)
compute_modular_elasticities_second E_target = compute_modular_elasticities_second(z,kinetic_law,N, W, ind_ext, alpha_A, alpha_I, alpha_M, v, A, u, c, h, v_plus_fallback, v_minus_fallback)
elasticities_to_parameters kinetics = elasticities_to_parameters(network,E_sc,v,c,u,A,h)
modular_fast_parameters pars = modular_fast_parameters(N,W,ind_ext,KA,KI,KM,KV,Keq,h)
modular_velocities [v, v_plus, v_minus] = modular_velocities(kinetic_law,N,W,ind_ext,u,c,KA,KI,KM,KV,Keq,h,Mplus, Mminus, Wplus, Wminus, nm, nr)
compute_rp_elasticities E = compute_ms_elasticities(N, W, ext_ind, alpha_A, alpha_I, alpha_M, vplus, vminus, u, c)
compute_ms_elasticities E = compute_ms_elasticities(N, W, ext_ind, alpha_A, alpha_I, alpha_M, vplus, vminus, u, c)
SOURCE CODE
function [Mplus, Mminus, Wplus, Wminus, nm, nr, N_int,ind_M,ind_Wp,ind_Wm,ind_Mp,ind_Mm] = make_structure_matrices(N,W,ind_ext,h)
% [Mplus, Mminus, Wplus, Wminus, nm, nr, N_int,ind_M,ind_Wp,ind_Wm] = make_structure_matrices(N,W,ind_ext,h)
eval(default('ind_first_order','[]','h','[]'));
N = sparse(N);
W = double(sparse(W));
[nm,nr] = size(N);
if isempty(h),
  h = ones(nr,1);
end
Mplus   = diag(h) * [abs(N').*(N'<0)];
Mminus  = diag(h) * [    N' .*(N'>0)];
Wplus   =     W .*(W>0);
Wminus  = abs(W).*(W<0);
N_int  = N(setdiff(1:nm,ind_ext),:);
ind_M  = find(Mplus+Mminus);
ind_Wp = find(Wplus);
ind_Wm = find(Wminus);
ind_Mp  = find(Mplus);
ind_Mm  = find(Mminus);