Description of network_find_metabolites
Home > mnt > mnt_network > network_query > network_find_metabolites.m
network_find_metabolites
PURPOSE
indices = network_find_metabolites(network,metabolites)
SYNOPSIS
function ind = network_find_metabolites(network,metabolite)
DESCRIPTION
indices = network_find_metabolites(network,metabolites)
INPUT
metabolites: metabolite name or list of metabolite names
CROSS-REFERENCE INFORMATION
This function calls:
label_names function [label,indices] = label_names(names,allnames, method)
This function is called by:
netgraph_simple_graph [n2,keep_met,keep_react] = netgraph_simple_graph(n1,met_hide,met_fixed,positions)
network_add_reaction network = network_add_reaction(network,reactants,stoich_coeffs,name,reversible);
network_merge_metabolites
network_set_all_external [network,ind] = network_set_all_external(network,metabolite_list)
network_set_external network = network_set_external(network,strict,metabolite_list,internal_list)
SOURCE CODE
%indices = network_find_metabolites(network,metabolites)
%
%INPUT
%metabolites: metabolite name or list of metabolite names
function ind = network_find_metabolites(network,metabolite)
if isstr(metabolite), metabolite={metabolite}; end
ind=label_names(metabolite,network.metabolites,'single');