Description of network_analyse
Home > mnt > mnt_network > network_query > network_analyse.m
network_analyse
PURPOSE
NETWORK_ANALYSE - Analyse a metabolic network structure
SYNOPSIS
function [K, L, N_R, G, pinv_N_R, indep, N_1] = network_analyse(network)
DESCRIPTION
 NETWORK_ANALYSE - Analyse a metabolic network structure
   [K, L, N_R, G, pinv_N_R, indep, N_1] = network_analyse(network)
   K        kernel matrix                   Def.   N * K  = 0
   L        link matrix                     Def.   L * NR = N_internal
   N_R      reduced stoichiometric matrix
            related to the independent metabolites
   G        left kernel matrix              Def.   G * N = 0
   pinv_N_R pseudoinverse of NR
   indep    indices of independent metabolites
   N_1      stoiciometric matrix for dependent metabolites
CROSS-REFERENCE INFORMATION
This function calls:
analyse_N [ K, L, NR, null_l, pinv_NR, independent_metabolites, N1] = analyse_N(N,external)
This function is called by:
es_mu_simple_guess [A, mu, exitflag] = es_mu_simple_guess(N,v,es_constraints,zv,flag_reduce_network)
flux2entropy_production [mu,A,R] = flux2entropy_production(network,v,mu_ext)
network_enzyme_subsets [enzyme_subsets,equilibrium_reactions,K] = network_enzyme_subsets(network);
network_print_conservation_relations network_print_conservation_relations(network,G)
SOURCE CODE
% NETWORK_ANALYSE - Analyse a metabolic network structure
%
%   [K, L, N_R, G, pinv_N_R, indep, N_1] = network_analyse(network)
%
%   K        kernel matrix                   Def.   N * K  = 0
%   L        link matrix                     Def.   L * NR = N_internal
%   N_R      reduced stoichiometric matrix
%            related to the independent metabolites
%   G        left kernel matrix              Def.   G * N = 0
%   pinv_N_R pseudoinverse of NR
%   indep    indices of independent metabolites
%   N_1      stoiciometric matrix for dependent metabolites
function [K, L, N_R, G, pinv_N_R, indep, N_1] = network_analyse(network)
N = full(network.N);
switch nargout,
  case 1,     K                                    = analyse_N(N,network.external);
  case {2,3}, [K, L, N_R]                          = analyse_N(N,network.external);
  case 4,     [K, L, N_R, G]                       = analyse_N(N,network.external);
  otherwise,  [K, L, N_R, G, pinv_N_R, indep, N_1] = analyse_N(N,network.external);
end