Description of fba_update_constraints
Home > mnt > mnt-basic > mnt_fluxes > fba > fba_update_constraints.m
fba_update_constraints
PURPOSE
fba_constraints = fba_update_constraints(fba_constraints)
SYNOPSIS
function fba_constraints = fba_update_constraints(fba_constraints,network)
DESCRIPTION
 fba_constraints = fba_update_constraints(fba_constraints)
 make fba constraints consistent
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
fba [v,benefit] = fba(network,fba_constraints)
moma [v,benefit] = moma(network,fba_constraints)
pmf v = pmf(network,fba_constraints,benefit,v_start)
pmf_quadratic v = pmf_quadratic(network,fba_constraints,benefit)
pmf_with_internal_production v = pmf(network,fba_constraints,benefit,v_start)