Description of cs_get_formula
Home > mnt > mnt-basic > mnt_kinetics > modular_rate_laws > cs_rate_law > cs_get_formula.m
cs_get_formula
PURPOSE
r_name reaction name (for naming the parameters)
SYNOPSIS
function formula = cs_get_formula(r_name,mn,sub,pro,act,inh,m_sub,m_pro)
DESCRIPTION
 r_name reaction name (for naming the parameters)
 mn: list of metabolite names
 sub, pro, act, inh indices of substrates, products, activators and inhibitors
 m_sub, m_pro  absolute values of stoichiometric coefficients for substrates and products
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
modular_kinetic_formulae [formula, global_assignment, local_assignment] = modular_kinetic_formulae(network)
network_get_kinetics_strings
network_sbml_export SBMLmodel = network_sbml_export(network, verbose, name, filename, notes, sbml_level, sbml_version)