Description of parameter_balancing_constrained_sampling
Home > mnt-advanced > mnt_parameter_balancing > parameter_balancing > parameter_balancing_constrained_sampling.m
parameter_balancing_constrained_sampling
PURPOSE
[q_sample, xmodel_sample, xdata_sample, kinetics_sample, v_sample, q_min, q_max] = parameter_balancing_constrained_sampling(task,res,options,quantity_info)
SYNOPSIS
function [q_sample, xmodel_sample, xdata_sample, kinetics_sample, v_sample, q_min, q_max] = parameter_balancing_constrained_sampling(task,res,options,quantity_info)
DESCRIPTION
 [q_sample, xmodel_sample, xdata_sample, kinetics_sample, v_sample, q_min, q_max] = parameter_balancing_constrained_sampling(task,res,options,quantity_info)
CROSS-REFERENCE INFORMATION
This function calls:
parameter_balancing_quantity_numbers count how many quantities of a certain type appear in a model
parameter_balancing_sample_models
network_numbers [nr,nm,nx,KM_indices,KA_indices,KI_indices,nKM,nKA,nKI] = network_numbers(network)
convex_sampling [x, x_lower. x_upper, success_flag, x_lower_list, x_upper_list] = convex_sampling(A_ineq,b_ineq,A_eq,b_eq,n_sample,xl,xu);
default commandstring = default(varname1,defaultvalue1,varname2,defaultvalue2,...)
join_struct c = join_struct(a,b)
This function is called by:
SOURCE CODE
function [q_sample, xmodel_sample, xdata_sample, kinetics_sample, v_sample, q_min, q_max] = parameter_balancing_constrained_sampling(task,res,options,quantity_info)
% [q_sample, xmodel_sample, xdata_sample, kinetics_sample, v_sample, q_min, q_max] = parameter_balancing_constrained_sampling(task,res,options,quantity_info)
eval(default('options','struct','quantity_info',' data_integration_load_quantity_info'));
options_default.n_sample = 1000;
options_default.n_warm   = [];
options_default.n_pick   = 10;
options_default.q_width  = 10;
options_default.compute_reaction_velocities = 0;
options_default.flag_artificial_centering = 0;
options_default.insert_pseudo_values = 0;
options_default.sampling_type = 'gaussian';
options_default.start_sampling_near_mode = 0;
options_default.try_rejection_sampling = 0;
options = join_struct(options_default,options);
% use all lower and upper values as explicit constraints
xconstraints = [-task.xlower.value_nat; ...
                 task.xupper.value_nat; ];
Qconstraints = [-task.Q_xlower_q; ...
                 task.Q_xupper_q;];
if options.insert_pseudo_values,
xconstraints = [xconstraints; ...
                -task.xall.lower_nat; ...
                 task.xall.upper_nat;];
Qconstraints = [Qconstraints; ...
                -task.Q_xall_q; ...
                 task.Q_xall_q];
end
ind_exact    = find(task.xdata.std < 10^-3);
if ind_exact,
  display('Data points with standard deviations <10^-3 found. Using equality constraints.');
  x_exact = task.xdata.mean(ind_exact);
  Q_exact = task.Q_xdata_q(ind_exact,:);
  ind_nonexact = find(task.xdata.std >= 10^-3);
else
  x_exact = [];
  Q_exact = [];
end
q_mode  = res.q_posterior.mode;
q_mean  = res.q_posterior.mean;
q_cov   = res.q_posterior.cov;
q_std   = sqrt(diag(q_cov));
q_lower = q_mode - options.q_width * q_std;
q_upper = q_mode + options.q_width * q_std;
if options.start_sampling_near_mode,
  q_start = res.q_posterior.mode;
else,
  q_start = [];
end
switch options.sampling_type,
  case 'gaussian',
    display('Running sampling with Gaussian distribution and constraints');
    %% call hit and run directly
    %% [q_sample, q_min, q_max] = convex_sampling_hit_and_run(Qconstraints, xconstraints, Q_exact, x_exact, q_lower, q_upper, q_mean, q_cov, options.n_sample, options.n_warm,options.n_pick,options.flag_artificial_centering, q_start);
    %% call convex_sampling (remove equality constraints first)
    ooptions         = options;
    ooptions.x_mean  = q_mean;
    ooptions.x_cov   = q_cov;
    ooptions.x_start = q_start;
    [q_sample, q_min, q_max] = convex_sampling(Qconstraints, xconstraints, Q_exact, x_exact, options.n_sample, q_lower, q_upper, 1, 'hit-and-run', ooptions);
  case 'uniform',
    display('Running uniform sampling');
    switch options.try_rejection_sampling,
      case 1,
        display('Using rejection sampling instead of hit-and run');
        [q_sample, q_min, q_max] = convex_sampling(Qconstraints, xconstraints, Q_exact, x_exact,options.n_sample,q_lower, q_upper,0);
      case 0,
        display('Using hit-and run sampling');
        %% call hit and run directly
        %% [q_sample, q_min, q_max] = convex_sampling_hit_and_run(Qconstraints, xconstraints, Q_exact, x_exact, q_lower, q_upper, [], [], options.n_sample, options.n_warm,options.n_pick,options.flag_artificial_centering, q_start );
        %% call convex_sampling (remove equality constraints first)
        ooptions         = options;
        ooptions.x_mean  = [];
        ooptions.x_cov   = [];
        ooptions.x_start = q_start;
        [q_sample, q_min, q_max] = convex_sampling(Qconstraints, xconstraints, Q_exact, x_exact,options.n_sample,q_lower, q_upper,1,'hit-and-run',ooptions);   end
end
xmodel_sample = task.Q_xmodel_q * q_sample;
xdata_sample  = task.Q_xdata_q  * q_sample;
% -----------------------------------------------------------------------
% translate the sampled model values back to kinetic constants
[nr,nm,nx,ind_KM,ind_KA,ind_KI,nKM,nKA,nKI] = network_numbers(task.network);
num_model = parameter_balancing_quantity_numbers(task.model_quantities,quantity_info,task.network);
for it = 1:length(task.model_quantities),
  my_quantity     = task.model_quantities{it};
  ind             = find(strcmp(my_quantity,quantity_info.QuantityType));
  my_scaling      = quantity_info.Scaling{ind};
  my_symbol       = quantity_info.Symbol{ind};
  my_indices      = task.xmodel.indices.(my_symbol);
  my_x_sample     = xmodel_sample(my_indices,:);
  if strcmp( my_scaling, 'Logarithmic'),
    my_x_sample   = exp(my_x_sample);
  else
    my_x_sample   = my_x_sample;
  end
  switch my_symbol,
    case 'KM', indices = ind_KM;
    case 'KA', indices = ind_KA;
    case 'KI', indices = ind_KI;
  end
  switch my_symbol,
    case {'KM'},
      my_x_sample  =  exp(xmodel_sample(task.xmodel.indices.KM,:));
    case {'KA'},
      my_x_sample  =  exp(xmodel_sample(task.xmodel.indices.KA,:));
    case {'KI'},
      my_x_sample  =  exp(xmodel_sample(task.xmodel.indices.KI,:));
  end
  kinetics_sample.(my_symbol)   = my_x_sample;
end
if options.compute_reaction_velocities,
  my_kinetics = task.network.kinetics;
  if strcmp('cs',my_kinetics.type),
    [v_sample] = parameter_balancing_sample_models(task,kinetics_sample,struct('sample_models','0'));
  else
    error('Kinetics not supported');
  end
else,
  v_sample = [];
end