Description of parameter_balancing_quantity_numbers
Home > mnt-advanced > mnt_parameter_balancing > parameter_balancing > parameter_balancing_quantity_numbers.m
parameter_balancing_quantity_numbers
PURPOSE
count how many quantities of a certain type appear in a model
SYNOPSIS
function num = parameter_balancing_quantity_numbers(quantities,quantity_info,network)
DESCRIPTION
 count how many quantities of a certain type appear in a model
CROSS-REFERENCE INFORMATION
This function calls:
network_numbers [nr,nm,nx,KM_indices,KA_indices,KI_indices,nKM,nKA,nKI] = network_numbers(network)
This function is called by:
parameter_balancing [res, exitflag] = parameter_balancing(task, quantity_info, options)
parameter_balancing_constrained_sampling [q_sample, xmodel_sample, xdata_sample, kinetics_sample, v_sample, q_min, q_max] = parameter_balancing_constrained_sampling(task,res,options,quantity_info)
parameter_balancing_construct_Q_matrix Q = parameter_balancing_construct_Q_matrix(quantities, basic_quantities, quantity_info, network)
parameter_balancing_task Prepare vectors and matrices for parameter balancing
SOURCE CODE
function num = parameter_balancing_quantity_numbers(quantities,quantity_info,network)
% count how many quantities of a certain type appear in a model
[nr,nm,nx,KM_indices,KA_indices,KI_indices,nKM,nKA,nKI] = network_numbers(network);
num=[];
for it = 1:length(quantities),
  my_quantity = quantities{it};
  ind = find(strcmp(my_quantity, quantity_info.QuantityType));
  my_elements = quantity_info.RelatedElement{ind};
  my_symbol   = quantity_info.Symbol{ind};
  switch  my_elements,
    case 'Species',  num(it,1) = nm;
    case 'Reaction', num(it,1) = nr;
    case 'Reaction/Species',
     switch my_symbol,
       case 'KM', num(it,1) = nKM;
       case 'KA', num(it,1) = nKA;
       case 'KI', num(it,1) = nKI;
       otherwise error(sprintf('Unknown symbol %s',my_symbol));
     end
  end
end