Description of pb_parameter_prior_adjust
Home > mnt-advanced > mnt_parameter_balancing > parameter_balancing > pb_parameter_prior_adjust.m
pb_parameter_prior_adjust
PURPOSE
SYNOPSIS
function parameter_prior = pb_parameter_prior_adjust(parameter_prior, options)
DESCRIPTION
CROSS-REFERENCE INFORMATION
This function calls:
label_names function [label,indices] = label_names(names,allnames, method)
This function is called by:
parameter_balancing_kinetic [r, r_orig, kinetic_data, r_samples, parameter_prior, r_mean, r_std,r_geom_mean,r_geom_std] = parameter_balancing_kinetic(network, kinetic_data, pb_options);
parameter_balancing_kinetic_metabolic [r, r_orig, kinetic_data, r_samples, parameter_prior, r_mean, r_std,r_geom_mean,r_geom_std] = parameter_balancing_kinetic(network, kinetic_data, file_kinetic_data, pb_options, v);
parameter_balancing_sbtab [network, r, r_orig, kinetic_data, r_samples, parameter_prior, r_mean, r_std] = parameter_balancing_sbtab(model_file, data_file, pb_options)