Description of network_adjust_names_for_sbml_export
Home > mnt > mnt_network > network_import_export > network_adjust_names_for_sbml_export.m
network_adjust_names_for_sbml_export
PURPOSE
[metabolites,actions] = network_adjust_names_for_sbml_export(metabolites,actions)
SYNOPSIS
function [metabolites,actions] = network_adjust_names_for_sbml_export(metabolites,actions)
DESCRIPTION
 [metabolites,actions] = network_adjust_names_for_sbml_export(metabolites,actions)
CROSS-REFERENCE INFORMATION
This function calls:
default commandstring = default(varname1,defaultvalue1,varname2,defaultvalue2,...)
This function is called by:
modular_rate_law_to_sbtab quantity_table = modular_rate_law_to_sbtab(network,filename,options)
sbtab_to_modular_rate_law [kinetics, kinetic_data] = sbtab_to_modular_rate_law(network,file_kinetic_data,options)
network_sbml_export SBMLmodel = network_sbml_export(network,verbose,name,filename,notes,sbml_level,sbml_version)
SOURCE CODE
function [metabolites,actions] = network_adjust_names_for_sbml_export(metabolites,actions)
% [metabolites,actions] = network_adjust_names_for_sbml_export(metabolites,actions)
eval(default('actions','[]'));
for it=1:length(metabolites),
  metabolites{it} = strrep(metabolites{it},'''','_');
  metabolites{it} = strrep(metabolites{it},'-','_');
  metabolites{it} = strrep(metabolites{it},':','_');
  metabolites{it} = strrep(metabolites{it},',','_');
  metabolites{it} = strrep(metabolites{it},'.','_');
  metabolites{it} = strrep(metabolites{it},' ','_');
  metabolites{it} = strrep(metabolites{it},'+','plus');
  metabolites{it} = strrep(metabolites{it},'(','_');
  metabolites{it} = strrep(metabolites{it},')','_');
  metabolites{it} = strrep(metabolites{it},'[','_');
  metabolites{it} = strrep(metabolites{it},']','_');
  metabolites{it} = strrep(metabolites{it},'<','_');
  metabolites{it} = strrep(metabolites{it},'/','_');
  metabolites{it} = strrep(metabolites{it},'[','_');
  metabolites{it} = strrep(metabolites{it},']','_');
  if length(strfind('0123456789',metabolites{it}(1)))
    metabolites{it} = ['_' metabolites{it}];
  end
end
for it=1:length(actions),
  actions{it} = strrep(actions{it},':','_');
  actions{it} = strrep(actions{it},' ','_');
  actions{it} = strrep(actions{it},'=','-');
  actions{it} = strrep(actions{it},'<->','_rev_');
  actions{it} = strrep(actions{it},'->','_irrev_');
  actions{it} = strrep(actions{it},'-','_');
  actions{it} = strrep(actions{it},',','_');
  actions{it} = strrep(actions{it},'.','_');
  actions{it} = strrep(actions{it},'(','_');
  actions{it} = strrep(actions{it},')','_');
  actions{it} = strrep(actions{it},'.','_');
  actions{it} = strrep(actions{it},'+','plus');
  actions{it} = strrep(actions{it},'[','_');
  actions{it} = strrep(actions{it},']','_');
  if length(strfind('0123456789',actions{it}(1)))
    actions{it} = ['_' actions{it}];
  end
end